"use client";

import { useState, useTransition } from "react";
import { Mail, Power } from "lucide-react";
import AdminCard from "@/components/admin/common/AdminCard";
import { AdminButton, AdminListHeader, AdminListRow, AdminModuleEmptyState, AdminModuleHeader, AdminModuleList, AdminModulePage, AdminSectionTitle, AdminStatusChip } from "@/components/admin/design-system";
import { disableAllNotificationEmailTypesAction, restoreRecommendedNotificationEmailTypesAction, updateNotificationEmailMasterAction, updateNotificationEmailTypeAction } from "@/app/admin/system/notification-email-settings/actions";
import { notificationEmailSettingGroups } from "./notificationEmailSettings.core.mjs";

function Toggle({ checked, disabled, label, onChange }) {
  return <button type="button" role="switch" aria-checked={checked} aria-label={`${label} ${checked ? "deaktivieren" : "aktivieren"}`} disabled={disabled} onClick={onChange} className={`relative h-11 w-16 shrink-0 rounded-full border transition focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-400 disabled:opacity-50 ${checked ? "border-emerald-400/50 bg-emerald-500/35" : "border-white/15 bg-white/5"}`}><span className={`absolute top-1.5 h-7 w-7 rounded-full bg-white transition ${checked ? "left-7" : "left-1.5"}`} /></button>;
}

export default function NotificationEmailSettingsModule({ initialSettings = null, loadError = null }) {
  const [settings, setSettings] = useState(initialSettings);
  const [message, setMessage] = useState("");
  const [pending, startTransition] = useTransition();
  const run = (action, apply) => startTransition(async () => { const result = await action(); setMessage(result.message); if (result.ok) setSettings((current) => apply(current, result.data)); });
  if (!settings) return <AdminModulePage><AdminModuleHeader eyebrow="System" title="E-Mail-Benachrichtigungen" description="Globale Steuerung des zusätzlichen E-Mail-Kanals." /><AdminModuleEmptyState icon={Mail} title="Einstellungen nicht verfügbar" description={loadError || "Die globalen E-Mail-Einstellungen konnten nicht geladen werden."} /></AdminModulePage>;
  const confirmAndRun = (question, action) => { if (window.confirm(question)) run(action, (_current, data) => data); };
  return <AdminModulePage>
    <AdminModuleHeader eyebrow="System" title="E-Mail-Benachrichtigungen" description="Steuere den automatischen E-Mail-Versand zusätzlich zu den Dashboard-Benachrichtigungen." />
    <AdminCard className={`border p-5 ${settings.masterEnabled ? "border-emerald-400/35" : "border-amber-400/30"}`}><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-white/5"><Power size={22} /></span><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-black">E-Mail-Benachrichtigungen global</h2><AdminStatusChip variant={settings.masterEnabled ? "success" : "warning"}>{settings.masterEnabled ? "AKTIV" : "DEAKTIVIERT"}</AdminStatusChip></div><p className="mt-2 max-w-3xl text-sm leading-6 text-white/55">Ist dieser Schalter deaktiviert, werden keine automatischen Notification-E-Mails versendet. Dashboard-Benachrichtigungen bleiben weiterhin aktiv.</p></div></div><Toggle checked={settings.masterEnabled} disabled={pending} label="Globalen E-Mail-Versand" onChange={() => run(() => updateNotificationEmailMasterAction(!settings.masterEnabled), (current, data) => ({ ...current, masterEnabled: data.enabled }))} /></div></AdminCard>
    <div className="flex flex-wrap gap-3"><AdminButton disabled={pending} onClick={() => confirmAndRun("Master und alle 27 E-Mail-Typen wirklich deaktivieren?", disableAllNotificationEmailTypesAction)}>Alle Typen deaktivieren</AdminButton><AdminButton disabled={pending} onClick={() => confirmAndRun("Empfohlene 16/11-Einstellungen wiederherstellen? Der globale Master bleibt AUS.", restoreRecommendedNotificationEmailTypesAction)}>Empfohlene Einstellungen</AdminButton></div>
    {message ? <p role="status" className="text-sm text-white/65">{message}</p> : null}
    {!settings.masterEnabled ? <p className="rounded-xl border border-amber-400/20 bg-amber-400/5 px-4 py-3 text-sm text-amber-100/75">Global AUS – die Typauswahl ist vorbereitet, hat derzeit aber keine Versandwirkung.</p> : null}
    {notificationEmailSettingGroups.map((group) => { const items = settings.items.filter((item) => item.group === group.key); const change = (item) => run(() => updateNotificationEmailTypeAction(item.type, !item.enabled), (current, data) => ({ ...current, items: current.items.map((entry) => entry.type === data.type ? { ...entry, enabled: data.enabled } : entry) })); return <section key={group.key} className="space-y-3"><AdminSectionTitle title={group.label} /><AdminModuleList desktopClassName="hidden overflow-hidden lg:block" mobile={<AdminCard className="divide-y divide-white/10 p-0 lg:hidden">{items.map((item) => <div key={item.type} className="flex items-center justify-between gap-3 px-3 py-3"><div className="min-w-0"><p className="text-sm font-bold text-white">{item.label}</p><p className="mt-0.5 text-xs leading-4 text-white/50">{item.description}</p><code className="mt-1 block break-all text-[0.68rem] text-white/35">{item.type}</code></div><Toggle checked={item.enabled} disabled={pending} label={item.label} onChange={() => change(item)} /></div>)}</AdminCard>}><AdminListHeader template="minmax(12rem,.9fr) minmax(16rem,1.35fr) minmax(12rem,.8fr) 4rem" columns={[{ key: "event", label: "Ereignis" }, { key: "description", label: "Beschreibung" }, { key: "type", label: "Type-Key" }, { key: "email", label: "E-Mail" }]} /><div className="divide-y divide-white/10">{items.map((item) => <AdminListRow key={item.type} template="minmax(12rem,.9fr) minmax(16rem,1.35fr) minmax(12rem,.8fr) 4rem" className="border-t-0 px-4 py-2.5"><span className="font-bold text-white">{item.label}</span><span className="text-xs leading-5 text-white/50">{item.description}</span><code className="break-all text-[0.68rem] text-white/35">{item.type}</code><Toggle checked={item.enabled} disabled={pending} label={item.label} onChange={() => change(item)} /></AdminListRow>)}</div></AdminModuleList></section>; })}
  </AdminModulePage>;
}
