"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import AdminCard from "@/components/admin/common/AdminCard";
import { AdminButton, AdminListHeader, AdminListMobileCard, AdminListRow, AdminMetric, AdminModuleCards, AdminModuleFilters, AdminModuleHeader, AdminModuleList, AdminModulePage, AdminModuleSearch, AdminModuleSummary, AdminSectionTitle, AdminStatusChip } from "@/components/admin/design-system";

const template = "1.1fr 1fr .8fr .6fr .5fr .5fr .5fr .6fr 1fr .8fr";
const formatDate = (value) => value ? new Date(value).toLocaleString("de-DE") : "–";
const shortId = (value) => value ? `${String(value).slice(0, 8)}…` : "–";
const variant = (status) => status === "success" ? "success" : status === "failed" ? "danger" : status === "duplicate" ? "warning" : "neutral";

function AuditCard({ item }) {
  return <AdminListMobileCard><div className="flex items-start justify-between gap-3"><div><p className="font-black text-white">{item.type}</p><p className="mt-1 text-xs text-white/45">{formatDate(item.timestamp)}</p></div><AdminStatusChip compact variant={variant(item.status)}>{item.status}</AdminStatusChip></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-white/60"><span>Actor: {shortId(item.actorId)}</span><span>Empfänger: {item.recipientCount}</span><span>Erfolgreich: {item.successCount}</span><span>Fehler: {item.failedCount}</span><span>Duplikate: {item.duplicateCount}</span><span>Dauer: {item.durationMs ?? "–"} ms</span></div><p className="mt-3 break-all text-xs text-white/45">{item.route || "/admin/notifications"}</p></AdminListMobileCard>;
}

export default function NotificationMonitoringModule({ initialEntries = [], initialHealth = {}, initialRecipientAnalysis = {}, initialTopErrors = [], initialActiveTypes = [], initialFilters = {}, loadError = null }) {
  const router = useRouter();
  const [search, setSearch] = useState(initialFilters.search || "");
  const status = initialFilters.status || "all";
  const range = initialFilters.range || "seven";
  const update = (next) => router.replace(`/admin/system/notifications?${new URLSearchParams({ search, status, range, ...next })}`);
  const entries = useMemo(() => initialEntries, [initialEntries]);

  return <AdminModulePage>
    <AdminModuleHeader eyebrow="System" title="Notification Monitoring" description="Zustellungen, Fehler und Auditinformationen dauerhaft überwachen." actions={<AdminButton disabled title="Retry ist vorbereitet, aber noch nicht freigegeben">Erneut zustellen</AdminButton>}><AdminModuleSearch value={search} onChange={(event) => setSearch(event.target.value)} onBlur={() => update({ search })} placeholder="Typ, Actor, Empfänger, Route oder Fehler suchen …" /></AdminModuleHeader>
    {loadError ? <AdminCard className="border-red-500/35 p-4 text-sm text-red-200">Auditdaten konnten nicht geladen werden: {loadError}</AdminCard> : null}
    <section className="space-y-4"><AdminSectionTitle eyebrow="Health" title="Notification Health" description="Vollständig aus dem persistenten Audit berechnete Zustellqualität." /><AdminModuleSummary><AdminMetric label="Erfolgreich" value={initialHealth.successful || 0} /><AdminMetric label="Fehlgeschlagen" value={initialHealth.failures || 0} /><AdminMetric label="Duplikate" value={initialHealth.duplicates || 0} /><AdminMetric label="Übersprungen" value={initialHealth.skipped || 0} /><AdminMetric label="Actor entfernt" value={initialHealth.actorRemoved || 0} /></AdminModuleSummary><div className="flex flex-wrap gap-3 text-sm text-white/55"><span>Letzter Erfolg: {formatDate(initialHealth.lastSuccess)}</span><span>Letzter Fehler: {formatDate(initialHealth.lastFailure)}</span><AdminStatusChip variant={variant(initialHealth.status)}>{initialHealth.status === "warning" ? "Warning" : "Success"}</AdminStatusChip></div></section>
    <AdminModuleFilters title="Audit filtern" panelId="monitor-filter"><div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-bold text-white/65">Status<select className="h-11 rounded-xl border border-white/10 bg-[#17171d] px-3" value={status} onChange={(event) => update({ status: event.target.value })}><option value="all">Alle</option><option value="success">Success</option><option value="failed">Failed</option><option value="duplicate">Duplicate</option><option value="warning">Skipped / Warning</option></select></label><label className="grid gap-2 text-sm font-bold text-white/65">Zeitraum<select className="h-11 rounded-xl border border-white/10 bg-[#17171d] px-3" value={range} onChange={(event) => update({ range: event.target.value })}><option value="today">Heute</option><option value="seven">7 Tage</option><option value="thirty">30 Tage</option><option value="ninety">90 Tage</option><option value="all">Alle</option></select></label></div></AdminModuleFilters>
    <div className="grid gap-5 xl:grid-cols-2"><AdminCard className="p-5"><AdminSectionTitle title="Top Fehler" />{initialTopErrors.length ? <div className="mt-4 space-y-2">{initialTopErrors.map((item) => <div key={item.errorClass} className="flex justify-between gap-3 border-t border-white/10 py-2 text-sm"><span>{item.errorClass}</span><strong>{item.count}</strong></div>)}</div> : <p className="mt-4 text-sm text-white/45">Keine Fehler im gewählten Zeitraum.</p>}</AdminCard><AdminCard className="p-5"><AdminSectionTitle title="Aktivste Notificationtypen" /><div className="mt-4 space-y-2">{initialActiveTypes.map((item) => <div key={item.type} className="grid grid-cols-[1fr_auto] gap-3 border-t border-white/10 py-2 text-sm"><span>{item.type}</span><strong>{item.count}</strong><span className="text-xs text-white/45">Letzte Zustellung: {formatDate(item.lastDelivery)}</span><span className="text-xs text-white/45">Fehlerquote: {(Number(item.errorRate || 0) * 100).toFixed(1)} %</span></div>)}</div></AdminCard></div>
    <section className="space-y-4"><AdminSectionTitle eyebrow="Audit" title="Zustellungs-Audit" description="Persistente, nicht editierbare Zustellungs- und Fehlerdaten." /><AdminModuleList desktopClassName="hidden overflow-hidden xl:block" mobile={<AdminModuleCards className="xl:hidden">{entries.map((item) => <AuditCard key={item.id} item={item} />)}</AdminModuleCards>}><AdminListHeader template={template} columns={[{key:"time",label:"Zeit"},{key:"type",label:"Eventtyp"},{key:"actor",label:"Actor"},{key:"recipients",label:"Empf."},{key:"success",label:"OK"},{key:"failed",label:"Fehler"},{key:"duplicate",label:"Dupl."},{key:"duration",label:"Dauer"},{key:"route",label:"Routing"},{key:"error",label:"Fehlerklasse"}]} />{entries.map((item) => <AdminListRow key={item.id} template={template}><span className="text-xs text-white/55">{formatDate(item.timestamp)}</span><span className="min-w-0"><span className="block truncate font-bold">{item.type}</span><AdminStatusChip compact variant={variant(item.status)}>{item.status}</AdminStatusChip></span><span>{shortId(item.actorId)}</span><span>{item.recipientCount}</span><span>{item.successCount}</span><span>{item.failedCount}</span><span>{item.duplicateCount}</span><span>{item.durationMs ?? "–"} ms</span><span className="truncate text-xs text-white/50">{item.route}</span><span className="truncate text-xs text-white/50">{item.errorClass || "–"}</span></AdminListRow>)}</AdminModuleList></section>
    <AdminCard className="p-5"><AdminSectionTitle title="Empfängeranalyse" description="Dauerhaft gespeicherte Resolver-Stufen im gewählten Zeitraum." /><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><AdminMetric label="Resolver-Eingang" value={initialRecipientAnalysis.resolverInput || 0} /><AdminMetric label="Gefundene Trainer" value={initialRecipientAnalysis.foundTrainers || 0} /><AdminMetric label="Aktive Trainer" value={initialRecipientAnalysis.activeTrainers || 0} /><AdminMetric label="Adminprofile" value={initialRecipientAnalysis.adminProfiles || 0} /><AdminMetric label="AuthUser" value={initialRecipientAnalysis.validAuthUsers || 0} /><AdminMetric label="Nach Actorfilter" value={initialRecipientAnalysis.afterActorFilter || 0} /><AdminMetric label="Nach Deduplizierung" value={initialRecipientAnalysis.afterDedupe || 0} /><AdminMetric label="Gespeichert" value={initialRecipientAnalysis.storedNotifications || 0} /></div></AdminCard>
    <AdminCard className="p-5"><AdminSectionTitle title="Retry-Vorbereitung" description="Retry-Felder sind vorhanden; erneute Zustellung bleibt deaktiviert." /><AdminButton disabled className="mt-4">Erneut zustellen</AdminButton></AdminCard>
    <AdminCard className="p-5"><AdminSectionTitle title="Benutzereinstellungen" description="Technische Preference-Zähler im gewählten Zeitraum." /><div className="mt-4 grid gap-3 sm:grid-cols-3"><AdminMetric label="Vor Preference-Filter" value={initialRecipientAnalysis.preferenceInput || 0} /><AdminMetric label="Durch Benutzereinstellung übersprungen" value={initialRecipientAnalysis.preferenceSkipped || 0} /><AdminMetric label="Nach Preference-Filter" value={initialRecipientAnalysis.preferenceOutput || 0} /></div></AdminCard>
  </AdminModulePage>;
}
