import { AdminListChevron, AdminListHeader, AdminListMobileCard, AdminListRow, AdminModuleCards, AdminModuleEmptyState, AdminModuleList, AdminStatusChip } from "@/components/admin/design-system";

const template = "minmax(0,1.4fr) minmax(0,1fr) minmax(0,.7fr) 2rem";
const columns = ["Empfänger", "Anfrageart", "Status", ""].map((label) => ({ key: label || "overview", label }));

export default function MembershipRecipientList({ membershipRecipients, selectedMembershipRecipientId, onSelectRecipient, getMembershipRequestTypeLabel }) {
  if (!membershipRecipients.length) return <AdminModuleEmptyState title="Keine Empfänger" description="Es wurden noch keine Empfänger für Mitgliedsanfragen angelegt." />;
  const status = (item) => <AdminStatusChip variant={item.is_active ? "success" : "warning"}>{item.is_active ? "Aktiv" : "Inaktiv"}</AdminStatusChip>;
  const mobile = <AdminModuleCards className="xl:hidden">{membershipRecipients.map((item) => <AdminListMobileCard key={item.id} onClick={() => onSelectRecipient(item)} label={`${item.label || item.email} bearbeiten`} className={selectedMembershipRecipientId === item.id ? "border-red-500/70 bg-red-600/10" : ""}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-black text-white">{item.label || item.email}</p><p className="mt-1 break-all text-sm text-white/55">{item.email}</p></div><AdminListChevron label="Übersicht" /></div><div className="mt-3 flex flex-wrap gap-2">{status(item)}<span className="text-sm text-white/60">{getMembershipRequestTypeLabel(item.request_type)}</span></div></AdminListMobileCard>)}</AdminModuleCards>;
  return <AdminModuleList mobile={mobile} desktopClassName="hidden overflow-hidden xl:block"><AdminListHeader columns={columns} template={template} />{membershipRecipients.map((item) => <AdminListRow key={item.id} onClick={() => onSelectRecipient(item)} label={`${item.label || item.email} bearbeiten`} template={template} className={selectedMembershipRecipientId === item.id ? "bg-red-600/10" : ""}><span className="min-w-0"><strong className="block truncate text-white">{item.label || item.email}</strong><span className="block truncate text-xs text-white/50">{item.email}</span></span><span className="truncate text-white/65">{getMembershipRequestTypeLabel(item.request_type)}</span>{status(item)}<AdminListChevron label="Übersicht" /></AdminListRow>)}</AdminModuleList>;
}
