import { InputField } from "@/components/admin/forms";
import Can from "@/components/admin/auth/Can";
import AdminRichTextEditor from "@/components/admin/richtext/AdminRichTextEditor";
import { AdminActionBar, AdminButton, AdminDangerZone, AdminDetailHeader, AdminDetailLayout, AdminInformationRow, AdminInformationSection, AdminStatusChip } from "@/components/admin/design-system";

export default function PageForm({ selectedPage, pageForm: form, pageLoading: loading, onSubmit, onFieldChange, onSlugChange, onReset, onDelete, onAutoSlug }) {
  const title = selectedPage ? (form.title_de || form.slug) : "Neue Seite";
  return <form onSubmit={onSubmit}><AdminDetailLayout header={<AdminDetailHeader backHref="/admin/settings?tab=pages" backLabel="Zurück zu Seiten" backVariant="pill" eyebrow="CMS" title={title} status={<AdminStatusChip variant={form.is_published ? "success" : "warning"}>{form.is_published ? "Veröffentlicht" : "Entwurf"}</AdminStatusChip>} meta={form.slug ? `/${form.slug}` : "Neue statische Seite"} />} dangerZone={selectedPage ? <Can permission="settings.edit" uiOnly><AdminDangerZone title="Seite löschen" description="Die bestehende Seite wird dauerhaft entfernt."><AdminButton variant="danger" onClick={onDelete}>Seite löschen</AdminButton></AdminDangerZone></Can> : null}>
    <AdminInformationSection title="Seitendaten"><AdminInformationRow label="Identität"><div className="grid gap-4 lg:grid-cols-2"><InputField label="Slug" required value={form.slug} onChange={(event) => onSlugChange(event.target.value)} className="h-11" /><InputField label="Titel" required value={form.title_de} onChange={(event) => onFieldChange("title_de", event.target.value)} onBlur={onAutoSlug} className="h-11" /></div></AdminInformationRow><AdminInformationRow label="Darstellung"><div className="grid gap-3 sm:grid-cols-3"><label className="flex min-h-11 items-center gap-3 rounded-2xl border border-white/10 bg-black/20 px-4 text-sm text-white/75"><input type="checkbox" checked={form.is_published} onChange={(event) => onFieldChange("is_published", event.target.checked)} />Veröffentlicht</label><label className="flex min-h-11 items-center gap-3 rounded-2xl border border-white/10 bg-black/20 px-4 text-sm text-white/75"><input type="checkbox" checked={form.show_in_footer} onChange={(event) => onFieldChange("show_in_footer", event.target.checked)} />Im Footer</label><InputField label="Sortierung" type="number" value={form.sort_order} onChange={(event) => onFieldChange("sort_order", Number(event.target.value || 0))} className="h-11" /></div></AdminInformationRow></AdminInformationSection>
    <AdminInformationSection title="Deutscher Inhalt"><AdminInformationRow label="Inhalt"><div className="min-w-0"><AdminRichTextEditor label="Inhalt (DE)" value={form.content_de} placeholder="Hier den deutschen Seitentext pflegen..." onChange={(value) => onFieldChange("content_de", value)} /></div></AdminInformationRow></AdminInformationSection>
    <Can permission="settings.edit" uiOnly><AdminActionBar className="justify-end"><AdminButton onClick={onReset}>Neue Seite</AdminButton><AdminButton type="submit" variant="primary" disabled={loading}>{loading ? "Speichert..." : "Seite speichern"}</AdminButton></AdminActionBar></Can>
  </AdminDetailLayout></form>;
}
