"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { InputField } from "@/components/admin/forms";
import { AdminActionBar, AdminButton, AdminDangerZone, AdminDetailHeader, AdminDetailLayout, AdminInformationRow, AdminInformationSection, AdminListChevron, AdminListHeader, AdminListMobileCard, AdminListRow, AdminMetric, AdminModuleCards, AdminModuleEmptyState, AdminModuleFilters, AdminModuleHeader, AdminModuleList, AdminModulePage, AdminModuleSummary, AdminStatusChip } from "@/components/admin/design-system";
import { deleteCategoryMasterDataAction, saveCategoryMasterDataAction } from "@/app/admin/settings/categories/actions";
import { CATEGORY_GROUPS, categorySummary, filterCategories } from "./categoryMasterData.core";

const TEMPLATE = "minmax(0,1.2fr) minmax(0,1fr) minmax(0,.6fr) minmax(0,.55fr) 2rem";
const COLUMNS = ["Name", "Technischer Schlüssel", "Status", "Sortierung", ""].map((label, index) => ({ key: `${index}-${label}`, label }));
const emptyForm = () => ({ name_de: "", name_en: "", slug: "", is_active: true, sort_order: 0 });

function CategoryEditor({ groupKey, item, onClose }) {
  const router = useRouter(); const group = CATEGORY_GROUPS[groupKey];
  const [form, setForm] = useState(() => ({ ...emptyForm(), ...(item || {}) })); const [loading, setLoading] = useState(false); const [message, setMessage] = useState("");
  const update = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  async function submit(event) { event.preventDefault(); setLoading(true); setMessage(""); const result = await saveCategoryMasterDataAction(groupKey, form, item?.id); setLoading(false); if (result.error) return setMessage(result.error.message); router.refresh(); onClose(); }
  async function remove() { if (!item?.id || item.is_system || !window.confirm("Eintrag wirklich löschen?")) return; setLoading(true); const result = await deleteCategoryMasterDataAction(groupKey, item.id); setLoading(false); if (result.error) return setMessage(result.error.message); router.refresh(); onClose(); }
  const danger = item ? <AdminDangerZone title={`${group.singular} löschen`} description={item.is_system ? "Dieser technische Systemtyp kann nicht gelöscht oder deaktiviert werden." : "Der Eintrag wird dauerhaft entfernt. Spätere fachliche Verwendungsschutzregeln bleiben davon unberührt."}>{item.is_system ? <AdminStatusChip variant="warning">Geschützter Systemtyp</AdminStatusChip> : <AdminButton type="button" variant="danger" disabled={loading} onClick={remove}>Löschen</AdminButton>}</AdminDangerZone> : null;
  return <form onSubmit={submit}><AdminDetailLayout header={<AdminDetailHeader backHref="/admin/settings/categories" backLabel="Zurück zur Übersicht" backVariant="pill" eyebrow={group.title} title={item ? form.name_de : `Neue ${group.singular}`} status={<AdminStatusChip variant={form.is_active ? "success" : "warning"}>{form.is_active ? "Aktiv" : "Inaktiv"}</AdminStatusChip>} meta={form.slug || "Neuer Stammdatensatz"} />} dangerZone={danger}><AdminInformationSection title="Stammdaten"><AdminInformationRow label="Deutscher Name"><InputField label="Deutscher Name" required value={form.name_de} onChange={(event) => update("name_de", event.target.value)} /></AdminInformationRow><AdminInformationRow label="Englischer Name"><InputField label="Englischer Name (optional)" value={form.name_en || ""} onChange={(event) => update("name_en", event.target.value)} /></AdminInformationRow><AdminInformationRow label="Technischer Schlüssel"><InputField label="Slug" required value={form.slug} disabled={Boolean(item?.is_system)} onChange={(event) => update("slug", event.target.value)} /></AdminInformationRow><AdminInformationRow label="Verwaltung"><div className="grid gap-4 sm:grid-cols-2"><InputField label="Sortierung" type="number" value={form.sort_order} onChange={(event) => update("sort_order", Number(event.target.value || 0))} /><label className="flex min-h-11 items-center gap-3 rounded-2xl border border-white/10 bg-black/20 px-4 text-sm text-white/75"><input type="checkbox" checked={form.is_active} disabled={Boolean(item?.is_system)} onChange={(event) => update("is_active", event.target.checked)} />Aktiv</label></div></AdminInformationRow>{message ? <AdminInformationRow label="Hinweis"><p role="alert" className="text-sm text-red-300">{message}</p></AdminInformationRow> : null}</AdminInformationSection><AdminActionBar className="justify-end"><AdminButton type="button" onClick={onClose}>Abbrechen</AdminButton><AdminButton type="submit" variant="primary" disabled={loading}>{loading ? "Speichert…" : "Speichern"}</AdminButton></AdminActionBar></AdminDetailLayout></form>;
}

export default function CategoryMasterDataModule({ initialData = {}, unavailable = false }) {
  const [groupKey, setGroupKey] = useState("news"); const [status, setStatus] = useState("all"); const [editor, setEditor] = useState(null);
  const group = CATEGORY_GROUPS[groupKey]; const items = useMemo(() => initialData[groupKey] || [], [initialData, groupKey]);
  const visible = useMemo(() => filterCategories(items, status), [items, status]); const summary = categorySummary(items);
  if (unavailable) return <AdminModulePage><AdminModuleHeader eyebrow="Einstellungen" title="Kategorien & Terminarten" description="Zentrale Stammdaten verwalten." /><AdminModuleEmptyState title="Datenbankgrundlage noch nicht verfügbar" description="Führe zuerst die geprüften H2-SQL-Dateien aus und lade die Seite anschließend neu." /></AdminModulePage>;
  if (editor) return <AdminModulePage><CategoryEditor key={`${groupKey}-${editor.id || "new"}`} groupKey={groupKey} item={editor.id ? editor : null} onClose={() => setEditor(null)} /></AdminModulePage>;
  const cards = <AdminModuleCards className="xl:hidden">{visible.map((item) => <AdminListMobileCard key={item.id} onClick={() => setEditor(item)} label={`${item.name_de} bearbeiten`}><div className="flex items-start justify-between gap-3"><div><p className="font-black text-white">{item.name_de}</p><p className="mt-1 text-sm text-white/55">{item.slug}</p></div><AdminListChevron label="Bearbeiten" /></div><div className="mt-3 flex gap-2"><AdminStatusChip compact variant={item.is_active ? "success" : "warning"}>{item.is_active ? "Aktiv" : "Inaktiv"}</AdminStatusChip>{item.is_system ? <AdminStatusChip compact variant="info">Systemtyp</AdminStatusChip> : null}</div></AdminListMobileCard>)}</AdminModuleCards>;
  return <AdminModulePage><AdminModuleHeader eyebrow="Einstellungen" title="Zentrale Kategorien" description="News-Kategorien, Terminarten und Download-Kategorien verwalten." actions={<AdminButton variant="primary" onClick={() => setEditor(emptyForm())}>Neue Kategorie</AdminButton>}><nav aria-label="Stammdatenbereiche" className="flex flex-wrap gap-2">{Object.entries(CATEGORY_GROUPS).map(([key, value]) => <AdminButton key={key} variant={key === groupKey ? "primary" : "secondary"} onClick={() => { setGroupKey(key); setStatus("all"); }}>{value.title}</AdminButton>)}</nav></AdminModuleHeader><AdminModuleSummary><AdminMetric label="Gesamt" value={summary.total} /><AdminMetric label="Aktiv" value={summary.active} /><AdminMetric label="Inaktiv" value={summary.inactive} /></AdminModuleSummary><AdminModuleFilters title={`${group.title} filtern`} panelId="category-master-filter"><label className="grid max-w-xs gap-2 text-sm font-bold text-white/65">Status<select className="h-11 rounded-xl border border-white/10 bg-[#17171d] px-3" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">Alle</option><option value="active">Aktiv</option><option value="inactive">Inaktiv</option></select></label></AdminModuleFilters>{visible.length ? <AdminModuleList mobile={cards} desktopClassName="hidden overflow-hidden xl:block"><AdminListHeader columns={COLUMNS} template={TEMPLATE} />{visible.map((item) => <AdminListRow key={item.id} onClick={() => setEditor(item)} label={`${item.name_de} bearbeiten`} template={TEMPLATE}><span className="font-black text-white">{item.name_de}</span><span className="text-white/60">{item.slug}</span><AdminStatusChip compact variant={item.is_active ? "success" : "warning"}>{item.is_active ? "Aktiv" : "Inaktiv"}</AdminStatusChip><span className="text-white/60">{item.sort_order || 0}</span><AdminListChevron label="Bearbeiten" /></AdminListRow>)}</AdminModuleList> : <AdminModuleEmptyState title={`Keine ${group.title}`} description="Für den gewählten Filter sind keine Einträge vorhanden." />}</AdminModulePage>;
}
