-- B15.19I1.1 read-only postcheck. Safe before or after the I1 media proposal.
SELECT c.relname,c.relrowsecurity,c.relforcerowsecurity FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname IN('club_history_pages','club_history_images','club_history_milestones') ORDER BY c.relname;
SELECT tablename,policyname,permissive,roles,cmd,qual,with_check FROM pg_policies WHERE schemaname='public' AND tablename IN('club_history_pages','club_history_images','club_history_milestones') ORDER BY tablename,cmd,policyname;
SELECT tablename,policyname,roles,cmd browser_write_policy_must_be_empty FROM pg_policies WHERE schemaname='public' AND tablename IN('club_history_pages','club_history_images','club_history_milestones') AND cmd IN('ALL','INSERT','UPDATE','DELETE') AND roles && ARRAY['public','anon','authenticated']::name[] ORDER BY tablename,policyname;
SELECT expected.tablename,expected.policyname,(actual.policyname IS NOT NULL) public_read_policy_present FROM (VALUES('club_history_pages','club_history_pages_public_read'),('club_history_images','club_history_images_public_read'),('club_history_milestones','club_history_milestones_public_read')) expected(tablename,policyname) LEFT JOIN pg_policies actual ON actual.schemaname='public' AND actual.tablename=expected.tablename AND actual.policyname=expected.policyname AND actual.cmd='SELECT' ORDER BY expected.tablename;
SELECT table_name,role_name,privilege_type,has_table_privilege(role_name,format('public.%I',table_name),privilege_type) effective_privilege FROM (SELECT unnest(ARRAY['club_history_pages','club_history_images','club_history_milestones']) table_name) t CROSS JOIN (SELECT unnest(ARRAY['anon','authenticated','service_role']) role_name) r CROSS JOIN (SELECT unnest(ARRAY['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER']) privilege_type) p ORDER BY table_name,role_name,privilege_type;
SELECT column_name,is_nullable,data_type FROM information_schema.columns WHERE table_schema='public' AND table_name='club_history_images' AND column_name IN('image_url','image_path','media_asset_id') ORDER BY column_name;
SELECT conname,pg_get_constraintdef(oid) FROM pg_constraint WHERE conrelid='public.club_history_images'::regclass AND (conname='club_history_images_media_asset_id_fkey' OR pg_get_constraintdef(oid) ILIKE '%media_asset%') ORDER BY conname;
SELECT indexname,indexdef FROM pg_indexes WHERE schemaname='public' AND tablename='club_history_images' AND indexdef ILIKE '%media_asset_id%' ORDER BY indexname;
SELECT tgname,pg_get_triggerdef(oid) FROM pg_trigger WHERE tgrelid='public.club_history_images'::regclass AND NOT tgisinternal ORDER BY tgname;
SELECT count(*) club_history_usage_count FROM public.media_asset_usages WHERE entity_type='club_history';
