-- B15.19G2 read-only postcheck. No writes.
SELECT column_name,data_type,is_nullable FROM information_schema.columns WHERE table_schema='public' AND table_name='event_documents' ORDER BY ordinal_position;
SELECT conname,contype,pg_get_constraintdef(oid) FROM pg_constraint WHERE conrelid IN('public.event_documents'::regclass,'public.media_asset_usages'::regclass) ORDER BY conrelid::regclass::text,conname;
SELECT indexname,indexdef FROM pg_indexes WHERE schemaname='public' AND tablename='event_documents';
SELECT pg_get_functiondef('public.synchronize_media_assignment(text,uuid,uuid,text)'::regprocedure);
SELECT tgname,pg_get_triggerdef(oid) FROM pg_trigger WHERE tgrelid='public.event_documents'::regclass AND NOT tgisinternal;
SELECT has_function_privilege('anon','public.synchronize_media_assignment(text,uuid,uuid,text)','EXECUTE') anon_must_be_false,has_function_privilege('authenticated','public.synchronize_media_assignment(text,uuid,uuid,text)','EXECUTE') authenticated_must_be_false,has_function_privilege('service_role','public.synchronize_media_assignment(text,uuid,uuid,text)','EXECUTE') service_role_must_be_true;
SELECT count(*) total,count(*) FILTER(WHERE media_asset_id IS NULL AND (file_path IS NOT NULL OR file_url IS NOT NULL)) legacy_documents,count(*) FILTER(WHERE media_asset_id IS NOT NULL) central_documents,count(*) FILTER(WHERE media_asset_id IS NOT NULL AND (file_path IS NOT NULL OR file_url IS NOT NULL)) dual_reference_documents,count(*) FILTER(WHERE media_asset_id IS NULL AND file_path IS NULL AND file_url IS NULL) without_source FROM public.event_documents;
SELECT count(DISTINCT file_path) distinct_paths,count(DISTINCT file_url) distinct_urls FROM public.event_documents WHERE file_path IS NOT NULL OR file_url IS NOT NULL;
SELECT file_path,file_url,count(*) FROM public.event_documents WHERE file_path IS NOT NULL OR file_url IS NOT NULL GROUP BY file_path,file_url HAVING count(*)>1 ORDER BY count(*) DESC;
SELECT ed.id,ed.media_asset_id,ma.media_kind,ma.visibility,ma.is_archived FROM public.event_documents ed LEFT JOIN public.media_assets ma ON ma.id=ed.media_asset_id WHERE ed.media_asset_id IS NOT NULL AND (ma.id IS NULL OR ma.media_kind<>'document' OR ma.is_archived OR (ed.is_public AND ma.visibility<>'public'));
SELECT ed.id FROM public.event_documents ed LEFT JOIN public.media_asset_usages u ON u.entity_type='event_document' AND u.entity_id=ed.id AND u.field_name='file' AND u.media_asset_id=ed.media_asset_id WHERE ed.media_asset_id IS NOT NULL AND u.id IS NULL;
SELECT u.* FROM public.media_asset_usages u LEFT JOIN public.event_documents ed ON ed.id=u.entity_id WHERE u.entity_type='event_document' AND (ed.id IS NULL OR ed.media_asset_id IS DISTINCT FROM u.media_asset_id OR u.field_name<>'file');
SELECT ed.id,ma.id possible_asset_id FROM public.event_documents ed JOIN public.media_assets ma ON ed.media_asset_id IS NULL AND (ma.storage_path=ed.file_path OR ma.original_filename=ed.file_name) ORDER BY ed.id;
