export const ADMIN_ROLE_KEYS = [
  "superadmin",
  "vorstand",
  "fussball-vorstand",
  "jugendleiter",
  "trainer",
  "betreuer",
  "redakteur",
  "kassierer",
  "webmaster",
  "gast",
];

export const ADMIN_PERMISSION_KEYS = [
  "dashboard.view",
  "news.view",
  "news.create",
  "news.edit",
  "news.delete",
  "news.publish",
  "events.view",
  "events.create",
  "events.edit",
  "events.delete",
  "events.publish",
  "teams.view",
  "teams.create",
  "teams.edit",
  "teams.delete",
  "players.view",
  "players.create",
  "players.edit",
  "players.delete",
  "coaches.view",
  "coaches.create",
  "coaches.edit",
  "coaches.delete",
  "sponsors.view",
  "sponsors.create",
  "sponsors.edit",
  "sponsors.delete",
  "club_history.view",
  "club_history.edit",
  "club_history.publish",
  "settings.view",
  "settings.edit",
  "membership_requests.view",
  "membership_requests.edit",
  "membership_requests.forward",
  "users.view",
  "users.create",
  "users.edit",
  "users.delete",
  "roles.view",
  "roles.edit",
  "system.view",
];

export const ADMIN_PERMISSION_GROUPS = {
  dashboard: ["dashboard.view"],
  news: [
    "news.view",
    "news.create",
    "news.edit",
    "news.delete",
    "news.publish",
  ],
  events: [
    "events.view",
    "events.create",
    "events.edit",
    "events.delete",
    "events.publish",
  ],
  teams: ["teams.view", "teams.create", "teams.edit", "teams.delete"],
  players: ["players.view", "players.create", "players.edit", "players.delete"],
  coaches: ["coaches.view", "coaches.create", "coaches.edit", "coaches.delete"],
  sponsors: [
    "sponsors.view",
    "sponsors.create",
    "sponsors.edit",
    "sponsors.delete",
  ],
  clubHistory: [
    "club_history.view",
    "club_history.edit",
    "club_history.publish",
  ],
  settings: ["settings.view", "settings.edit"],
  membershipRequests: [
    "membership_requests.view",
    "membership_requests.edit",
    "membership_requests.forward",
  ],
  users: ["users.view", "users.create", "users.edit", "users.delete"],
  roles: ["roles.view", "roles.edit"],
  system: ["system.view"],
};
