"use client";

import { useMemo, useState, useTransition } from "react";
import { Download, FileText, Pencil, Trash2 } from "lucide-react";
import Can from "@/components/admin/auth/Can";
import { AdminButton, AdminListHeader, AdminListMobileCard, AdminListRow, AdminMetric, AdminModuleCards, AdminModuleEmptyState, AdminModuleHeader, AdminModuleList, AdminModulePage, AdminModuleSearch, AdminModuleSummary } from "@/components/admin/design-system";
import AdminMediaPickerDialog from "@/components/admin/media-library/AdminMediaPickerDialog";
import AdminMediaPickerTrigger from "@/components/admin/media-library/AdminMediaPickerTrigger";
import { formatFileSize } from "@/lib/files";
import { deleteDownloadAction, loadDownloadMediaPickerAction, saveDownloadAction, toggleDownloadPublishedAction, uploadDownloadMediaAction } from "@/app/admin/downloads/actions";

const TEMPLATE="minmax(12rem,1.2fr) minmax(9rem,.8fr) minmax(12rem,1fr) 7rem 5rem 8rem minmax(15rem,auto)";
const emptyForm={id:null,title:"",description:"",categoryId:"",mediaAssetId:"",sortOrder:0,isPublished:false};
const toForm=(item)=>item?{id:item.id,title:item.title||"",description:item.description||"",categoryId:item.category_id||"",mediaAssetId:item.media_asset_id||"",sortOrder:item.sort_order||0,isPublished:Boolean(item.is_published)}:{...emptyForm};

function Status({published}){return <span className={`inline-flex w-fit rounded-full px-2.5 py-1 text-xs font-bold ${published?"bg-emerald-500/15 text-emerald-300":"bg-white/10 text-white/55"}`}>{published?"Veröffentlicht":"Entwurf"}</span>;}
function FileInfo({asset}){return <span className="min-w-0"><strong className="block truncate text-white/80">{asset?.display_name||asset?.original_filename||"Keine Datei"}</strong><span className="text-xs text-white/45">PDF · {formatFileSize(asset?.file_size_bytes)||"–"}</span></span>;}

function DownloadEditor({item,categories,onClose}){
  const [form,setForm]=useState(toForm(item)); const [asset,setAsset]=useState(item?.media_assets||null); const [pickerOpen,setPickerOpen]=useState(false); const [message,setMessage]=useState(null); const [pending,startTransition]=useTransition();
  const change=(key,value)=>setForm((current)=>({...current,[key]:value}));
  function save(){startTransition(async()=>{const result=await saveDownloadAction(form); if(result.ok){onClose(true);return;} setMessage(result.error);});}
  return <div role="dialog" aria-modal="true" aria-labelledby="download-editor-title" className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4"><section className="max-h-[94vh] w-full max-w-3xl overflow-y-auto rounded-3xl border border-white/15 bg-zinc-950 p-6 shadow-2xl md:p-8"><header className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.3em] text-red-400">Download</p><h2 id="download-editor-title" className="mt-2 text-2xl font-black">{item?"Download bearbeiten":"Download anlegen"}</h2></div><button type="button" onClick={()=>onClose(false)} className="rounded-full border border-white/15 px-4 py-2 text-sm font-bold">Abbrechen</button></header>
    <div className="mt-7 grid gap-5"><label className="grid gap-2 text-sm font-bold">Titel<input maxLength={200} value={form.title} onChange={(e)=>change("title",e.target.value)} className="rounded-2xl border border-white/10 bg-black/20 p-3"/></label><label className="grid gap-2 text-sm font-bold">Beschreibung<textarea maxLength={2000} rows={4} value={form.description} onChange={(e)=>change("description",e.target.value)} className="rounded-2xl border border-white/10 bg-black/20 p-3"/></label><div className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-bold">Kategorie<select value={form.categoryId} onChange={(e)=>change("categoryId",e.target.value)} className="rounded-2xl border border-white/10 bg-neutral-900 p-3"><option value="">Bitte auswählen</option>{categories.filter((category)=>category.is_active).map((category)=><option key={category.id} value={category.id}>{category.name_de}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Sortierung<input type="number" min="0" max="1000000" value={form.sortOrder} onChange={(e)=>change("sortOrder",Number(e.target.value))} className="rounded-2xl border border-white/10 bg-black/20 p-3"/></label></div>
    <section className="rounded-2xl border border-white/10 bg-white/[.03] p-4"><p className="text-sm font-bold">PDF-Datei</p><div className="mt-3 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3"><FileText className="text-red-300"/><FileInfo asset={asset}/></div><AdminMediaPickerTrigger onClick={()=>setPickerOpen(true)} label={asset?"PDF ersetzen":"PDF auswählen oder hochladen"}/></div></section>
    <Can permission="downloads.publish" uiOnly fallback={<div className="rounded-2xl border border-white/10 p-4"><Status published={form.isPublished}/></div>}><label className="flex items-center gap-3 rounded-2xl border border-white/10 p-4 text-sm font-bold"><input type="checkbox" checked={form.isPublished} onChange={(e)=>change("isPublished",e.target.checked)} className="h-5 w-5 accent-red-600"/>Veröffentlicht</label></Can>{message?<p role="alert" className="rounded-2xl bg-red-500/10 p-4 text-sm text-red-200">{message}</p>:null}<div className="flex justify-end gap-3"><AdminButton onClick={()=>onClose(false)}>Abbrechen</AdminButton><AdminButton variant="primary" disabled={pending} onClick={save}>{pending?"Speichert …":"Speichern"}</AdminButton></div></div>
    <AdminMediaPickerDialog open={pickerOpen} onClose={()=>setPickerOpen(false)} onSelect={(selected)=>{setAsset(selected);change("mediaAssetId",selected.id);}} loadAction={loadDownloadMediaPickerAction} uploadAction={uploadDownloadMediaAction} mediaKind="document" defaultPurpose="all"/>
  </section></div>;
}

function RowActions({item,onEdit,onRefresh}){const [pending,startTransition]=useTransition(); const run=(action)=>startTransition(async()=>{const result=await action(item.id); if(!result.ok)alert(result.error); else onRefresh();}); return <div className="flex items-center justify-end gap-2"><Can permission="downloads.edit" uiOnly><button type="button" title="Bearbeiten" onClick={()=>onEdit(item)} className="rounded-full border border-white/10 p-2 hover:border-red-400"><Pencil size={15}/></button></Can><Can permission="downloads.publish" uiOnly><button type="button" disabled={pending} onClick={()=>run(toggleDownloadPublishedAction)} className="rounded-full border border-white/10 px-3 py-2 text-xs font-bold">{item.is_published?"Deaktivieren":"Veröffentlichen"}</button></Can><Can permission="downloads.delete" uiOnly><button type="button" title="Löschen" disabled={pending} onClick={()=>{if(confirm(`„${item.title}“ dauerhaft löschen? Die Datei bleibt in der Medienbibliothek.`))run(deleteDownloadAction);}} className="rounded-full border border-red-500/20 p-2 text-red-300"><Trash2 size={15}/></button></Can></div>;}

export default function DownloadsModule({downloads=[],categories=[],loadError=null}){
  const [search,setSearch]=useState(""); const [editor,setEditor]=useState(undefined); const visible=useMemo(()=>downloads.filter((item)=>`${item.title} ${item.description||""} ${item.download_categories?.name_de||""}`.toLowerCase().includes(search.trim().toLowerCase())),[downloads,search]);
  const refresh=()=>window.location.reload();
  return <AdminModulePage><AdminModuleHeader eyebrow="Gesamtverein" title="Downloads verwalten" description="Öffentliche Download-Einträge und ihre privaten PDF-Dateien verwalten." actions={<Can permission="downloads.create" uiOnly><AdminButton variant="primary" onClick={()=>setEditor(null)}>+ Download anlegen</AdminButton></Can>}><AdminModuleSearch value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Downloads suchen …"/></AdminModuleHeader><AdminModuleSummary><AdminMetric label="Gesamt" value={downloads.length}/><AdminMetric label="Veröffentlicht" value={downloads.filter((item)=>item.is_published).length}/><AdminMetric label="Entwürfe" value={downloads.filter((item)=>!item.is_published).length}/><AdminMetric label="Kategorien" value={categories.filter((item)=>item.is_active).length}/></AdminModuleSummary>{loadError?<p role="alert" className="rounded-2xl bg-red-500/10 p-4 text-red-200">{loadError}</p>:null}{!visible.length?<AdminModuleEmptyState icon={Download} title={downloads.length?"Keine Downloads gefunden":"Noch keine Downloads angelegt"} description={downloads.length?"Passe den Suchbegriff an.":"Lege den ersten Download über den Primärbutton an."}/>:<AdminModuleList desktopClassName="hidden overflow-hidden xl:block" mobile={<AdminModuleCards className="xl:hidden">{visible.map((item)=><AdminListMobileCard key={item.id}><div className="flex gap-3"><FileText className="mt-1 shrink-0 text-red-300"/><div className="min-w-0 flex-1"><h2 className="font-black">{item.title}</h2><p className="mt-1 text-sm text-white/50">{item.download_categories?.name_de||"–"}</p><div className="mt-3"><FileInfo asset={item.media_assets}/></div><div className="mt-3 flex items-center justify-between gap-3"><Status published={item.is_published}/><RowActions item={item} onEdit={setEditor} onRefresh={refresh}/></div></div></div></AdminListMobileCard>)}</AdminModuleCards>}><AdminListHeader template={TEMPLATE} columns={[{key:"title",label:"Titel"},{key:"category",label:"Kategorie"},{key:"file",label:"Datei"},{key:"status",label:"Status"},{key:"sort",label:"Sort."},{key:"updated",label:"Aktualisiert"},{key:"actions",label:"Aktionen",className:"text-right"}]}/>{visible.map((item)=><AdminListRow key={item.id} template={TEMPLATE}><span className="truncate font-black">{item.title}</span><span className="truncate text-white/60">{item.download_categories?.name_de||"–"}</span><FileInfo asset={item.media_assets}/><Status published={item.is_published}/><span className="text-white/55">{item.sort_order}</span><span className="text-xs text-white/50">{item.updated_at?new Intl.DateTimeFormat("de-DE").format(new Date(item.updated_at)):"–"}</span><RowActions item={item} onEdit={setEditor} onRefresh={refresh}/></AdminListRow>)}</AdminModuleList>}{editor!==undefined?<DownloadEditor item={editor} categories={categories} onClose={(saved)=>{setEditor(undefined);if(saved)refresh();}}/>:null}</AdminModulePage>;
}
