import test from "node:test";
import assert from "node:assert/strict";
import { canChangePublished,classifyDownloadPickerAsset,isEligibleDownloadAsset,normalizeDownloadInput,sortDownloads,validateDownloadInput } from "./downloads.core.mjs";

const categoryId="11111111-1111-4111-8111-111111111111";
const mediaAssetId="22222222-2222-4222-8222-222222222222";

test("normalizes German download metadata and publication state",()=>{assert.deepEqual(normalizeDownloadInput({title:"  Satzung  ",description:"  Info ",categoryId,mediaAssetId,sortOrder:"7",isPublished:"true"}),{id:null,title:"Satzung",description:"Info",categoryId,mediaAssetId,sortOrder:7,isPublished:true});});
test("validates UUIDs, title, description and sort bounds",()=>{assert.equal(validateDownloadInput({title:"Satzung",categoryId,mediaAssetId,sortOrder:0}).ok,true); const invalid=validateDownloadInput({title:" ",categoryId:"x",mediaAssetId:"x",sortOrder:1000001}); assert.equal(invalid.ok,false); assert.deepEqual(Object.keys(invalid.errors).sort(),["categoryId","mediaAssetId","sortOrder","title"]);});
test("accepts only active private download PDFs",()=>{const asset={id:mediaAssetId,is_archived:false,media_kind:"document",mime_type:"application/pdf",storage_bucket:"media-library-private",visibility:"admin",purpose:"download"}; assert.equal(isEligibleDownloadAsset(asset),true); for(const patch of [{media_kind:"image"},{mime_type:"image/png"},{storage_bucket:"media-library-public"},{visibility:"public"},{purpose:"news"},{is_archived:true}]) assert.equal(isEligibleDownloadAsset({...asset,...patch}),false);});
test("picker shows all PDFs but selects only B15.22B-compliant assets",()=>{const base={id:mediaAssetId,is_archived:false,media_kind:"document",mime_type:"application/pdf",media_asset_usages:[]};assert.equal(classifyDownloadPickerAsset({...base,storage_bucket:"media-library-private",visibility:"admin",purpose:"download"}).selectable,true);const generic=classifyDownloadPickerAsset({...base,storage_bucket:"media-library-private",visibility:"admin",purpose:"document"});assert.equal(generic.visible,true);assert.equal(generic.selectable,false);assert.match(generic.reason,/Purpose-Übernahme/);const publicAsset=classifyDownloadPickerAsset({...base,storage_bucket:"media-library-public",visibility:"public",purpose:"document"});assert.equal(publicAsset.visible,true);assert.equal(publicAsset.selectable,false);assert.match(publicAsset.reason,/erneut privat/);});
test("used foreign PDFs remain visible but cannot be reclassified",()=>{const result=classifyDownloadPickerAsset({id:mediaAssetId,is_archived:false,media_kind:"document",mime_type:"application/pdf",storage_bucket:"media-library-private",visibility:"admin",purpose:"news",media_asset_usages:[{id:"usage"}]});assert.equal(result.selectable,false);assert.match(result.reason,/anderweitig verwendet/);assert.equal(classifyDownloadPickerAsset({id:mediaAssetId,is_archived:true,media_kind:"document",mime_type:"application/pdf"}).visible,false);assert.equal(classifyDownloadPickerAsset({id:mediaAssetId,is_archived:false,media_kind:"image",mime_type:"image/png"}).visible,false);});
test("sorts by category order, download order, title and id",()=>{const rows=[{id:"b",title:"Z",sort_order:2,category_sort_order:1},{id:"a",title:"A",sort_order:1,category_sort_order:1},{id:"c",title:"A",sort_order:0,category_sort_order:2}]; assert.deepEqual(sortDownloads(rows).map((row)=>row.id),["a","b","c"]);});
test("detects publication changes only for existing rows",()=>{assert.equal(canChangePublished(null,{isPublished:true}),false);assert.equal(canChangePublished({is_published:false},{isPublished:true}),true);assert.equal(canChangePublished({is_published:true},{isPublished:true}),false);});
