import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const read=(path)=>readFile(new URL(path,import.meta.url),"utf8");
const [service,repository,logger,monitor,center,idemSql,auditSql]=await Promise.all([read("../notifications.service.js"),read("../notifications.repository.js"),read("../monitoring/notificationMonitoring.logger.js"),read("../monitoring/NotificationMonitoringModule.js"),read("../NotificationsModule.js"),read("../../../../../docs/sql/b15-18i-notification-idempotency-hardening-proposal.sql"),read("../../../../../docs/sql/b15-18i-notification-audit-insert-hardening-proposal.sql")]);
test("current five-minute lookup is not misrepresented as concurrency-safe",()=>{ assert.match(service,/5 \* 60 \* 1000/); assert.match(repository,/loadPotentialDuplicateNotifications/); assert.match(idemSql,/CREATE UNIQUE INDEX/); assert.match(idemSql,/unique_violation/); });
test("audit hardening proposal removes direct insert and exposes only sanitized append RPC",()=>{ assert.match(auditSql,/REVOKE INSERT/); assert.match(auditSql,/SECURITY DEFINER/); assert.match(auditSql,/jsonb_build_object/); assert.doesNotMatch(auditSql,/service_role|app_metadata/); });
test("current logger accepts structured server events only and discards unknown fields",()=>{ assert.match(logger,/createAuditPayload/); for(const forbidden of ["title:","message:","email:","token:","stack:"]) assert.doesNotMatch(logger,new RegExp(forbidden,"i")); });
test("retry remains disabled and has no click handler",()=>{ assert.match(monitor,/disabled/); assert.doesNotMatch(monitor,/onClick=.*retry|retry.*Action/i); });
test("center and monitoring have bounded server loads",()=>{ assert.match(service,/limit = 100/); assert.match(center,/initialItems/); assert.match(monitor,/initialEntries/); });
