/**
 * Zentrale Länderliste für Nationalitäten.
 * Wird u. a. bei Spielern, Trainern, Vorstand und Mitgliedern verwendet.
 */
export const COUNTRIES = [
  { iso: "AF", flag: "🇦🇫", de: "Afghanistan", en: "Afghanistan" },
  { iso: "EG", flag: "🇪🇬", de: "Ägypten", en: "Egypt" },
  { iso: "AX", flag: "🇦🇽", de: "Ålandinseln", en: "Åland Islands" },
  { iso: "AL", flag: "🇦🇱", de: "Albanien", en: "Albania" },
  { iso: "DZ", flag: "🇩🇿", de: "Algerien", en: "Algeria" },
  { iso: "AS", flag: "🇦🇸", de: "Amerikanisch-Samoa", en: "American Samoa" },
  { iso: "VI", flag: "🇻🇮", de: "Amerikanische Jungferninseln", en: "U.S. Virgin Islands" },
  { iso: "AD", flag: "🇦🇩", de: "Andorra", en: "Andorra" },
  { iso: "AO", flag: "🇦🇴", de: "Angola", en: "Angola" },
  { iso: "AI", flag: "🇦🇮", de: "Anguilla", en: "Anguilla" },
  { iso: "AQ", flag: "🇦🇶", de: "Antarktis", en: "Antarctica" },
  { iso: "AG", flag: "🇦🇬", de: "Antigua und Barbuda", en: "Antigua and Barbuda" },
  { iso: "GQ", flag: "🇬🇶", de: "Äquatorialguinea", en: "Equatorial Guinea" },
  { iso: "AR", flag: "🇦🇷", de: "Argentinien", en: "Argentina" },
  { iso: "AM", flag: "🇦🇲", de: "Armenien", en: "Armenia" },
  { iso: "AW", flag: "🇦🇼", de: "Aruba", en: "Aruba" },
  { iso: "AZ", flag: "🇦🇿", de: "Aserbaidschan", en: "Azerbaijan" },
  { iso: "ET", flag: "🇪🇹", de: "Äthiopien", en: "Ethiopia" },
  { iso: "AU", flag: "🇦🇺", de: "Australien", en: "Australia" },
  { iso: "BS", flag: "🇧🇸", de: "Bahamas", en: "Bahamas" },
  { iso: "BH", flag: "🇧🇭", de: "Bahrain", en: "Bahrain" },
  { iso: "BD", flag: "🇧🇩", de: "Bangladesch", en: "Bangladesh" },
  { iso: "BB", flag: "🇧🇧", de: "Barbados", en: "Barbados" },
  { iso: "BY", flag: "🇧🇾", de: "Belarus", en: "Belarus" },
  { iso: "BE", flag: "🇧🇪", de: "Belgien", en: "Belgium" },
  { iso: "BZ", flag: "🇧🇿", de: "Belize", en: "Belize" },
  { iso: "BJ", flag: "🇧🇯", de: "Benin", en: "Benin" },
  { iso: "BM", flag: "🇧🇲", de: "Bermuda", en: "Bermuda" },
  { iso: "BT", flag: "🇧🇹", de: "Bhutan", en: "Bhutan" },
  { iso: "BO", flag: "🇧🇴", de: "Bolivien", en: "Bolivia" },
  { iso: "BQ", flag: "🇧🇶", de: "Bonaire, Sint Eustatius und Saba", en: "Bonaire, Sint Eustatius and Saba" },
  { iso: "BA", flag: "🇧🇦", de: "Bosnien und Herzegowina", en: "Bosnia and Herzegovina" },
  { iso: "BW", flag: "🇧🇼", de: "Botswana", en: "Botswana" },
  { iso: "BV", flag: "🇧🇻", de: "Bouvetinsel", en: "Bouvet Island" },
  { iso: "BR", flag: "🇧🇷", de: "Brasilien", en: "Brazil" },
  { iso: "VG", flag: "🇻🇬", de: "Britische Jungferninseln", en: "British Virgin Islands" },
  { iso: "IO", flag: "🇮🇴", de: "Britisches Territorium im Indischen Ozean", en: "British Indian Ocean Territory" },
  { iso: "BN", flag: "🇧🇳", de: "Brunei", en: "Brunei" },
  { iso: "BG", flag: "🇧🇬", de: "Bulgarien", en: "Bulgaria" },
  { iso: "BF", flag: "🇧🇫", de: "Burkina Faso", en: "Burkina Faso" },
  { iso: "BI", flag: "🇧🇮", de: "Burundi", en: "Burundi" },
  { iso: "CL", flag: "🇨🇱", de: "Chile", en: "Chile" },
  { iso: "CN", flag: "🇨🇳", de: "China", en: "China" },
  { iso: "CK", flag: "🇨🇰", de: "Cookinseln", en: "Cook Islands" },
  { iso: "CR", flag: "🇨🇷", de: "Costa Rica", en: "Costa Rica" },
  { iso: "CI", flag: "🇨🇮", de: "Côte d’Ivoire", en: "Côte d’Ivoire" },
  { iso: "CW", flag: "🇨🇼", de: "Curaçao", en: "Curaçao" },
  { iso: "DK", flag: "🇩🇰", de: "Dänemark", en: "Denmark" },
  { iso: "DE", flag: "🇩🇪", de: "Deutschland", en: "Germany" },
  { iso: "DM", flag: "🇩🇲", de: "Dominica", en: "Dominica" },
  { iso: "DO", flag: "🇩🇴", de: "Dominikanische Republik", en: "Dominican Republic" },
  { iso: "DJ", flag: "🇩🇯", de: "Dschibuti", en: "Djibouti" },
  { iso: "EC", flag: "🇪🇨", de: "Ecuador", en: "Ecuador" },
  { iso: "SV", flag: "🇸🇻", de: "El Salvador", en: "El Salvador" },
  { iso: "ER", flag: "🇪🇷", de: "Eritrea", en: "Eritrea" },
  { iso: "EE", flag: "🇪🇪", de: "Estland", en: "Estonia" },
  { iso: "SZ", flag: "🇸🇿", de: "Eswatini", en: "Eswatini" },
  { iso: "FK", flag: "🇫🇰", de: "Falklandinseln", en: "Falkland Islands" },
  { iso: "FO", flag: "🇫🇴", de: "Färöer", en: "Faroe Islands" },
  { iso: "FJ", flag: "🇫🇯", de: "Fidschi", en: "Fiji" },
  { iso: "FI", flag: "🇫🇮", de: "Finnland", en: "Finland" },
  { iso: "FR", flag: "🇫🇷", de: "Frankreich", en: "France" },
  { iso: "GF", flag: "🇬🇫", de: "Französisch-Guayana", en: "French Guiana" },
  { iso: "PF", flag: "🇵🇫", de: "Französisch-Polynesien", en: "French Polynesia" },
  { iso: "TF", flag: "🇹🇫", de: "Französische Süd- und Antarktisgebiete", en: "French Southern Territories" },
  { iso: "GA", flag: "🇬🇦", de: "Gabun", en: "Gabon" },
  { iso: "GM", flag: "🇬🇲", de: "Gambia", en: "Gambia" },
  { iso: "GE", flag: "🇬🇪", de: "Georgien", en: "Georgia" },
  { iso: "GH", flag: "🇬🇭", de: "Ghana", en: "Ghana" },
  { iso: "GI", flag: "🇬🇮", de: "Gibraltar", en: "Gibraltar" },
  { iso: "GD", flag: "🇬🇩", de: "Grenada", en: "Grenada" },
  { iso: "GR", flag: "🇬🇷", de: "Griechenland", en: "Greece" },
  { iso: "GL", flag: "🇬🇱", de: "Grönland", en: "Greenland" },
  { iso: "GP", flag: "🇬🇵", de: "Guadeloupe", en: "Guadeloupe" },
  { iso: "GU", flag: "🇬🇺", de: "Guam", en: "Guam" },
  { iso: "GT", flag: "🇬🇹", de: "Guatemala", en: "Guatemala" },
  { iso: "GG", flag: "🇬🇬", de: "Guernsey", en: "Guernsey" },
  { iso: "GN", flag: "🇬🇳", de: "Guinea", en: "Guinea" },
  { iso: "GW", flag: "🇬🇼", de: "Guinea-Bissau", en: "Guinea-Bissau" },
  { iso: "GY", flag: "🇬🇾", de: "Guyana", en: "Guyana" },
  { iso: "HT", flag: "🇭🇹", de: "Haiti", en: "Haiti" },
  { iso: "HM", flag: "🇭🇲", de: "Heard und McDonaldinseln", en: "Heard Island and McDonald Islands" },
  { iso: "HN", flag: "🇭🇳", de: "Honduras", en: "Honduras" },
  { iso: "HK", flag: "🇭🇰", de: "Hongkong", en: "Hong Kong" },
  { iso: "IN", flag: "🇮🇳", de: "Indien", en: "India" },
  { iso: "ID", flag: "🇮🇩", de: "Indonesien", en: "Indonesia" },
  { iso: "IM", flag: "🇮🇲", de: "Isle of Man", en: "Isle of Man" },
  { iso: "IQ", flag: "🇮🇶", de: "Irak", en: "Iraq" },
  { iso: "IR", flag: "🇮🇷", de: "Iran", en: "Iran" },
  { iso: "IE", flag: "🇮🇪", de: "Irland", en: "Ireland" },
  { iso: "IS", flag: "🇮🇸", de: "Island", en: "Iceland" },
  { iso: "IL", flag: "🇮🇱", de: "Israel", en: "Israel" },
  { iso: "IT", flag: "🇮🇹", de: "Italien", en: "Italy" },
  { iso: "JM", flag: "🇯🇲", de: "Jamaika", en: "Jamaica" },
  { iso: "JP", flag: "🇯🇵", de: "Japan", en: "Japan" },
  { iso: "YE", flag: "🇾🇪", de: "Jemen", en: "Yemen" },
  { iso: "JE", flag: "🇯🇪", de: "Jersey", en: "Jersey" },
  { iso: "JO", flag: "🇯🇴", de: "Jordanien", en: "Jordan" },
  { iso: "KY", flag: "🇰🇾", de: "Kaimaninseln", en: "Cayman Islands" },
  { iso: "KH", flag: "🇰🇭", de: "Kambodscha", en: "Cambodia" },
  { iso: "CM", flag: "🇨🇲", de: "Kamerun", en: "Cameroon" },
  { iso: "CA", flag: "🇨🇦", de: "Kanada", en: "Canada" },
  { iso: "CV", flag: "🇨🇻", de: "Kap Verde", en: "Cape Verde" },
  { iso: "KZ", flag: "🇰🇿", de: "Kasachstan", en: "Kazakhstan" },
  { iso: "QA", flag: "🇶🇦", de: "Katar", en: "Qatar" },
  { iso: "KE", flag: "🇰🇪", de: "Kenia", en: "Kenya" },
  { iso: "KG", flag: "🇰🇬", de: "Kirgisistan", en: "Kyrgyzstan" },
  { iso: "KI", flag: "🇰🇮", de: "Kiribati", en: "Kiribati" },
  { iso: "CC", flag: "🇨🇨", de: "Kokosinseln", en: "Cocos Islands" },
  { iso: "CO", flag: "🇨🇴", de: "Kolumbien", en: "Colombia" },
  { iso: "KM", flag: "🇰🇲", de: "Komoren", en: "Comoros" },
  { iso: "CG", flag: "🇨🇬", de: "Kongo", en: "Republic of the Congo" },
  { iso: "CD", flag: "🇨🇩", de: "Kongo, Demokratische Republik", en: "Democratic Republic of the Congo" },
  { iso: "KP", flag: "🇰🇵", de: "Korea, Nord", en: "North Korea" },
  { iso: "KR", flag: "🇰🇷", de: "Korea, Süd", en: "South Korea" },
  { iso: "XK", flag: "🇽🇰", de: "Kosovo", en: "Kosovo" },
  { iso: "HR", flag: "🇭🇷", de: "Kroatien", en: "Croatia" },
  { iso: "CU", flag: "🇨🇺", de: "Kuba", en: "Cuba" },
  { iso: "KW", flag: "🇰🇼", de: "Kuwait", en: "Kuwait" },
  { iso: "LA", flag: "🇱🇦", de: "Laos", en: "Laos" },
  { iso: "LS", flag: "🇱🇸", de: "Lesotho", en: "Lesotho" },
  { iso: "LV", flag: "🇱🇻", de: "Lettland", en: "Latvia" },
  { iso: "LB", flag: "🇱🇧", de: "Libanon", en: "Lebanon" },
  { iso: "LR", flag: "🇱🇷", de: "Liberia", en: "Liberia" },
  { iso: "LY", flag: "🇱🇾", de: "Libyen", en: "Libya" },
  { iso: "LI", flag: "🇱🇮", de: "Liechtenstein", en: "Liechtenstein" },
  { iso: "LT", flag: "🇱🇹", de: "Litauen", en: "Lithuania" },
  { iso: "LU", flag: "🇱🇺", de: "Luxemburg", en: "Luxembourg" },
  { iso: "MO", flag: "🇲🇴", de: "Macau", en: "Macao" },
  { iso: "MG", flag: "🇲🇬", de: "Madagaskar", en: "Madagascar" },
  { iso: "MW", flag: "🇲🇼", de: "Malawi", en: "Malawi" },
  { iso: "MY", flag: "🇲🇾", de: "Malaysia", en: "Malaysia" },
  { iso: "MV", flag: "🇲🇻", de: "Malediven", en: "Maldives" },
  { iso: "ML", flag: "🇲🇱", de: "Mali", en: "Mali" },
  { iso: "MT", flag: "🇲🇹", de: "Malta", en: "Malta" },
  { iso: "MA", flag: "🇲🇦", de: "Marokko", en: "Morocco" },
  { iso: "MH", flag: "🇲🇭", de: "Marshallinseln", en: "Marshall Islands" },
  { iso: "MQ", flag: "🇲🇶", de: "Martinique", en: "Martinique" },
  { iso: "MR", flag: "🇲🇷", de: "Mauretanien", en: "Mauritania" },
  { iso: "MU", flag: "🇲🇺", de: "Mauritius", en: "Mauritius" },
  { iso: "YT", flag: "🇾🇹", de: "Mayotte", en: "Mayotte" },
  { iso: "MX", flag: "🇲🇽", de: "Mexiko", en: "Mexico" },
  { iso: "FM", flag: "🇫🇲", de: "Mikronesien", en: "Micronesia" },
  { iso: "MD", flag: "🇲🇩", de: "Moldau", en: "Moldova" },
  { iso: "MC", flag: "🇲🇨", de: "Monaco", en: "Monaco" },
  { iso: "MN", flag: "🇲🇳", de: "Mongolei", en: "Mongolia" },
  { iso: "ME", flag: "🇲🇪", de: "Montenegro", en: "Montenegro" },
  { iso: "MS", flag: "🇲🇸", de: "Montserrat", en: "Montserrat" },
  { iso: "MZ", flag: "🇲🇿", de: "Mosambik", en: "Mozambique" },
  { iso: "MM", flag: "🇲🇲", de: "Myanmar", en: "Myanmar" },
  { iso: "NA", flag: "🇳🇦", de: "Namibia", en: "Namibia" },
  { iso: "NR", flag: "🇳🇷", de: "Nauru", en: "Nauru" },
  { iso: "NP", flag: "🇳🇵", de: "Nepal", en: "Nepal" },
  { iso: "NC", flag: "🇳🇨", de: "Neukaledonien", en: "New Caledonia" },
  { iso: "NZ", flag: "🇳🇿", de: "Neuseeland", en: "New Zealand" },
  { iso: "NI", flag: "🇳🇮", de: "Nicaragua", en: "Nicaragua" },
  { iso: "NL", flag: "🇳🇱", de: "Niederlande", en: "Netherlands" },
  { iso: "NE", flag: "🇳🇪", de: "Niger", en: "Niger" },
  { iso: "NG", flag: "🇳🇬", de: "Nigeria", en: "Nigeria" },
  { iso: "NU", flag: "🇳🇺", de: "Niue", en: "Niue" },
  { iso: "MK", flag: "🇲🇰", de: "Nordmazedonien", en: "North Macedonia" },
  { iso: "MP", flag: "🇲🇵", de: "Nördliche Marianen", en: "Northern Mariana Islands" },
  { iso: "NF", flag: "🇳🇫", de: "Norfolkinsel", en: "Norfolk Island" },
  { iso: "NO", flag: "🇳🇴", de: "Norwegen", en: "Norway" },
  { iso: "OM", flag: "🇴🇲", de: "Oman", en: "Oman" },
  { iso: "AT", flag: "🇦🇹", de: "Österreich", en: "Austria" },
  { iso: "PK", flag: "🇵🇰", de: "Pakistan", en: "Pakistan" },
  { iso: "PS", flag: "🇵🇸", de: "Palästina", en: "Palestine" },
  { iso: "PW", flag: "🇵🇼", de: "Palau", en: "Palau" },
  { iso: "PA", flag: "🇵🇦", de: "Panama", en: "Panama" },
  { iso: "PG", flag: "🇵🇬", de: "Papua-Neuguinea", en: "Papua New Guinea" },
  { iso: "PY", flag: "🇵🇾", de: "Paraguay", en: "Paraguay" },
  { iso: "PE", flag: "🇵🇪", de: "Peru", en: "Peru" },
  { iso: "PH", flag: "🇵🇭", de: "Philippinen", en: "Philippines" },
  { iso: "PN", flag: "🇵🇳", de: "Pitcairninseln", en: "Pitcairn Islands" },
  { iso: "PL", flag: "🇵🇱", de: "Polen", en: "Poland" },
  { iso: "PT", flag: "🇵🇹", de: "Portugal", en: "Portugal" },
  { iso: "PR", flag: "🇵🇷", de: "Puerto Rico", en: "Puerto Rico" },
  { iso: "RE", flag: "🇷🇪", de: "Réunion", en: "Réunion" },
  { iso: "RW", flag: "🇷🇼", de: "Ruanda", en: "Rwanda" },
  { iso: "RO", flag: "🇷🇴", de: "Rumänien", en: "Romania" },
  { iso: "RU", flag: "🇷🇺", de: "Russland", en: "Russia" },
  { iso: "BL", flag: "🇧🇱", de: "Saint-Barthélemy", en: "Saint Barthélemy" },
  { iso: "MF", flag: "🇲🇫", de: "Saint-Martin", en: "Saint Martin" },
  { iso: "PM", flag: "🇵🇲", de: "Saint-Pierre und Miquelon", en: "Saint Pierre and Miquelon" },
  { iso: "SB", flag: "🇸🇧", de: "Salomonen", en: "Solomon Islands" },
  { iso: "ZM", flag: "🇿🇲", de: "Sambia", en: "Zambia" },
  { iso: "WS", flag: "🇼🇸", de: "Samoa", en: "Samoa" },
  { iso: "SM", flag: "🇸🇲", de: "San Marino", en: "San Marino" },
  { iso: "ST", flag: "🇸🇹", de: "São Tomé und Príncipe", en: "São Tomé and Príncipe" },
  { iso: "SA", flag: "🇸🇦", de: "Saudi-Arabien", en: "Saudi Arabia" },
  { iso: "SE", flag: "🇸🇪", de: "Schweden", en: "Sweden" },
  { iso: "CH", flag: "🇨🇭", de: "Schweiz", en: "Switzerland" },
  { iso: "SN", flag: "🇸🇳", de: "Senegal", en: "Senegal" },
  { iso: "RS", flag: "🇷🇸", de: "Serbien", en: "Serbia" },
  { iso: "SC", flag: "🇸🇨", de: "Seychellen", en: "Seychelles" },
  { iso: "SL", flag: "🇸🇱", de: "Sierra Leone", en: "Sierra Leone" },
  { iso: "ZW", flag: "🇿🇼", de: "Simbabwe", en: "Zimbabwe" },
  { iso: "SG", flag: "🇸🇬", de: "Singapur", en: "Singapore" },
  { iso: "SX", flag: "🇸🇽", de: "Sint Maarten", en: "Sint Maarten" },
  { iso: "SK", flag: "🇸🇰", de: "Slowakei", en: "Slovakia" },
  { iso: "SI", flag: "🇸🇮", de: "Slowenien", en: "Slovenia" },
  { iso: "SO", flag: "🇸🇴", de: "Somalia", en: "Somalia" },
  { iso: "ES", flag: "🇪🇸", de: "Spanien", en: "Spain" },
  { iso: "SJ", flag: "🇸🇯", de: "Spitzbergen und Jan Mayen", en: "Svalbard and Jan Mayen" },
  { iso: "LK", flag: "🇱🇰", de: "Sri Lanka", en: "Sri Lanka" },
  { iso: "SH", flag: "🇸🇭", de: "St. Helena", en: "Saint Helena" },
  { iso: "KN", flag: "🇰🇳", de: "St. Kitts und Nevis", en: "Saint Kitts and Nevis" },
  { iso: "LC", flag: "🇱🇨", de: "St. Lucia", en: "Saint Lucia" },
  { iso: "VC", flag: "🇻🇨", de: "St. Vincent und die Grenadinen", en: "Saint Vincent and the Grenadines" },
  { iso: "ZA", flag: "🇿🇦", de: "Südafrika", en: "South Africa" },
  { iso: "SD", flag: "🇸🇩", de: "Sudan", en: "Sudan" },
  { iso: "GS", flag: "🇬🇸", de: "Südgeorgien und Südliche Sandwichinseln", en: "South Georgia and the South Sandwich Islands" },
  { iso: "SS", flag: "🇸🇸", de: "Südsudan", en: "South Sudan" },
  { iso: "SR", flag: "🇸🇷", de: "Suriname", en: "Suriname" },
  { iso: "SY", flag: "🇸🇾", de: "Syrien", en: "Syria" },
  { iso: "TJ", flag: "🇹🇯", de: "Tadschikistan", en: "Tajikistan" },
  { iso: "TW", flag: "🇹🇼", de: "Taiwan", en: "Taiwan" },
  { iso: "TZ", flag: "🇹🇿", de: "Tansania", en: "Tanzania" },
  { iso: "TH", flag: "🇹🇭", de: "Thailand", en: "Thailand" },
  { iso: "TL", flag: "🇹🇱", de: "Timor-Leste", en: "Timor-Leste" },
  { iso: "TG", flag: "🇹🇬", de: "Togo", en: "Togo" },
  { iso: "TK", flag: "🇹🇰", de: "Tokelau", en: "Tokelau" },
  { iso: "TO", flag: "🇹🇴", de: "Tonga", en: "Tonga" },
  { iso: "TT", flag: "🇹🇹", de: "Trinidad und Tobago", en: "Trinidad and Tobago" },
  { iso: "TD", flag: "🇹🇩", de: "Tschad", en: "Chad" },
  { iso: "CZ", flag: "🇨🇿", de: "Tschechien", en: "Czechia" },
  { iso: "TN", flag: "🇹🇳", de: "Tunesien", en: "Tunisia" },
  { iso: "TR", flag: "🇹🇷", de: "Türkei", en: "Turkey" },
  { iso: "TM", flag: "🇹🇲", de: "Turkmenistan", en: "Turkmenistan" },
  { iso: "TC", flag: "🇹🇨", de: "Turks- und Caicosinseln", en: "Turks and Caicos Islands" },
  { iso: "TV", flag: "🇹🇻", de: "Tuvalu", en: "Tuvalu" },
  { iso: "UG", flag: "🇺🇬", de: "Uganda", en: "Uganda" },
  { iso: "UA", flag: "🇺🇦", de: "Ukraine", en: "Ukraine" },
  { iso: "HU", flag: "🇭🇺", de: "Ungarn", en: "Hungary" },
  { iso: "UM", flag: "🇺🇲", de: "United States Minor Outlying Islands", en: "United States Minor Outlying Islands" },
  { iso: "UY", flag: "🇺🇾", de: "Uruguay", en: "Uruguay" },
  { iso: "UZ", flag: "🇺🇿", de: "Usbekistan", en: "Uzbekistan" },
  { iso: "VU", flag: "🇻🇺", de: "Vanuatu", en: "Vanuatu" },
  { iso: "VA", flag: "🇻🇦", de: "Vatikanstadt", en: "Vatican City" },
  { iso: "VE", flag: "🇻🇪", de: "Venezuela", en: "Venezuela" },
  { iso: "AE", flag: "🇦🇪", de: "Vereinigte Arabische Emirate", en: "United Arab Emirates" },
  { iso: "US", flag: "🇺🇸", de: "Vereinigte Staaten", en: "United States" },
  { iso: "GB", flag: "🇬🇧", de: "Vereinigtes Königreich", en: "United Kingdom" },
  { iso: "VN", flag: "🇻🇳", de: "Vietnam", en: "Vietnam" },
  { iso: "CX", flag: "🇨🇽", de: "Weihnachtsinsel", en: "Christmas Island" },
  { iso: "EH", flag: "🇪🇭", de: "Westsahara", en: "Western Sahara" },
  { iso: "CF", flag: "🇨🇫", de: "Zentralafrikanische Republik", en: "Central African Republic" },
  { iso: "CY", flag: "🇨🇾", de: "Zypern", en: "Cyprus" },
  { iso: "OTHER", flag: "🌍", de: "Sonstige", en: "Other" },
];

export function getCountryByIso(iso) {
  return COUNTRIES.find((country) => country.iso === iso) || null;
}

export function getCountryLabel(iso, locale = "de") {
  const country = getCountryByIso(iso);
  if (!country) return "";
  return `${country.flag} ${locale === "en" ? country.en : country.de}`;
}
