import Link from "next/link";
import { PublicCard } from "@/components/website/layout";

function formatDate(value) { if (!value) return "–"; const date = new Date(`${value}T12:00:00`); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("de-DE", { day: "2-digit", month: "2-digit", year: "numeric" }).format(date); }

function CompetitionTable({ rows, unavailable }) {
  return <PublicCard><p className="text-xs font-black uppercase tracking-[0.3em] text-red-400">Ligatabelle</p><h2 className="mt-3 text-2xl font-black sm:text-3xl">Tabelle</h2>{unavailable ? <p className="mt-5 text-white/60">Die aktuelle Tabelle ist momentan nicht verfügbar.</p> : rows?.length ? <div className="mt-6 max-w-full overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[760px] border-collapse text-left text-sm"><thead className="bg-white/5 text-xs uppercase tracking-wider text-white/45"><tr><th className="px-3 py-3">Platz</th><th className="px-3 py-3">Mannschaft</th><th className="px-3 py-3">Spiele</th><th className="px-3 py-3">S</th><th className="px-3 py-3">U</th><th className="px-3 py-3">N</th><th className="px-3 py-3">Spielverhältnis</th><th className="px-3 py-3">Sätze</th><th className="px-3 py-3">Punkte</th></tr></thead><tbody className="divide-y divide-white/10">{rows.map((row, index) => <tr key={`${row.rank}-${row.teamName}-${index}`} className={row.isOwnTeam ? "bg-red-500/12 font-bold" : ""}><td className="px-3 py-3">{row.rank ?? "–"}</td><td className="px-3 py-3"><span>{row.teamName}</span>{row.isOwnTeam ? <span className="ml-2 inline-flex rounded-full bg-red-500/20 px-2 py-0.5 text-[0.65rem] font-black uppercase tracking-wide text-red-200">Unsere Mannschaft</span> : null}</td><td className="px-3 py-3">{row.matchesPlayed ?? "–"}</td><td className="px-3 py-3">{row.wins ?? "–"}</td><td className="px-3 py-3">{row.draws ?? "–"}</td><td className="px-3 py-3">{row.losses ?? "–"}</td><td className="px-3 py-3">{row.score || "–"}</td><td className="px-3 py-3">{row.sets || row.difference || "–"}</td><td className="px-3 py-3">{row.points || "–"}</td></tr>)}</tbody></table></div> : <p className="mt-5 text-white/60">Aktuell sind keine Tabellenzeilen vorhanden.</p>}</PublicCard>;
}

function CompetitionSchedule({ rows, unavailable }) {
  return <PublicCard><p className="text-xs font-black uppercase tracking-[0.3em] text-red-400">Mannschaftsspielplan</p><h2 className="mt-3 text-2xl font-black sm:text-3xl">Spiele</h2>{unavailable ? <p className="mt-5 text-white/60">Der aktuelle Spielplan ist momentan nicht verfügbar.</p> : rows?.length ? <ul className="mt-6 space-y-3">{rows.map((match, index) => <li key={match.meetingId || `${match.date}-${index}`}><article className="grid min-w-0 gap-3 rounded-2xl border border-white/10 bg-white/[0.035] p-4 md:grid-cols-[9rem_minmax(0,1fr)_auto] md:items-center"><div><p className="font-black">{formatDate(match.date)}</p><p className="text-sm text-white/50">{match.time || "Uhrzeit offen"}</p></div><div className="min-w-0"><p className="break-words font-bold">{match.homeTeam || "–"}</p><p className="break-words text-white/60">{match.awayTeam || "–"}</p>{match.venue ? <p className="mt-1 break-words text-xs text-white/40">{match.venue}</p> : null}</div><div className="md:text-right"><p className="font-black">{match.result || match.status || "Offen"}</p><p className="text-xs text-white/45">{match.isHome ? "Heimspiel" : match.isAway ? "Auswärtsspiel" : ""}</p></div></article></li>)}</ul> : <p className="mt-5 text-white/60">Aktuell sind keine Spiele für diese Mannschaft vorhanden.</p>}</PublicCard>;
}

export default function TableTennisCompetitionView({ competition, notConfigured = false }) {
  if (notConfigured || !competition || competition.status === "not_configured" || competition.status === "inactive") return <PublicCard><h2 className="text-2xl font-black">Spielplan & Tabelle</h2><p className="mt-4 text-white/60">Für diese Mannschaft ist derzeit keine Spielbetriebsintegration hinterlegt.</p></PublicCard>;
  const allUnavailable = competition.status === "unavailable";
  return <section className="min-w-0 space-y-6"><div className="min-w-0 space-y-6"><CompetitionTable rows={competition.table} unavailable={allUnavailable || Boolean(competition.tableError)} /><CompetitionSchedule rows={competition.schedule} unavailable={allUnavailable || Boolean(competition.scheduleError)} /></div>{competition.attribution?.sourceUrl ? <p className="text-sm text-white/45">Daten: <Link href={competition.attribution.sourceUrl} target="_blank" rel="noreferrer" className="font-bold text-red-300 underline decoration-red-300/40 underline-offset-4 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-400">{competition.attribution.label}</Link></p> : null}</section>;
}
