import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const read=(path)=>readFile(new URL(path,import.meta.url),"utf8");
const [dialog,picker,repository,actions,form,sql]=await Promise.all([read("./AdminMediaPickerDialog.js"),read("./AdminMediaPicker.js"),read("./media.repository.js"),read("../../../app/admin/coaches/actions.js"),read("../coaches/forms/AdminCoachesForm.js"),read("../../../../docs/sql/b15-19b-coach-media-reference-proposal.sql")]);

test("picker is lazy, single-select, cancellable and server paginated",()=>{ assert.match(dialog,/if \(open[\s\S]*void load/); assert.match(dialog,/onSelect\(item\);\s*close\(\)/); assert.match(dialog,/Abbrechen/); assert.match(repository,/\.range\(from, from \+ safePageSize - 1\)/); assert.match(repository,/description\.ilike/); assert.match(repository,/mime_type\.ilike/); assert.match(repository,/purpose\.ilike/); });
test("coach picker rechecks scope and permits admin media only for media managers",()=>{ assert.match(actions,/assertAdminActionPermission/); assert.match(actions,/canEditCoachOnServer/); assert.match(actions,/canCreateCoachOnServer/); assert.match(actions,/canManageMedia\(auth\.permissionResult\.roles\) \? \["public", "admin"\] : \["public"\]/); assert.match(actions,/normalizePickerPurpose\(filters\.purpose, "coach"\)/); assert.match(actions,/kind: "image"[\s\S]*purpose[\s\S]*archived: "active"/); assert.match(repository,/\.in\("visibility", visibility\)/); assert.doesNotMatch(actions,/"restricted"/); assert.match(actions,/\["image\/jpeg", "image\/png", "image\/webp"\]/); });
test("picker search cannot submit the surrounding coach form",()=>{ assert.doesNotMatch(dialog,/<form\b|onSubmit=/); assert.match(dialog,/event\?\.preventDefault\(\)/); assert.match(dialog,/event\?\.stopPropagation\(\)/); assert.match(dialog,/<button type="button" onClick=\{search\}/); assert.match(dialog,/event\.key === "Enter"[\s\S]*search\(event\)/); });
test("coach form stores media id, supports replacement and removes only the link",()=>{ assert.match(form,/image_media_asset_id/); assert.match(form,/AdminMediaPicker/); assert.match(picker,/onChange\(null\)/); assert.doesNotMatch(picker,/storage\.from|supabase/); });
test("coach reference and one usage per image field are explicit",()=>{ assert.match(sql,/image_media_asset_id uuid NULL REFERENCES public\.media_assets/); assert.match(sql,/media_asset_usages_one_field_per_entity/); assert.doesNotMatch(sql,/UPDATE public\.coaches|DELETE FROM storage/); });
