"use client";
import { useState, useTransition } from "react";
import { Bell, CheckCircle2 } from "lucide-react";
import { disableAllOptionalNotificationsAction, enableAllOptionalNotificationsAction, resetNotificationPreferencesAction, updateNotificationPreferenceAction } from "@/app/admin/notifications/settings/actions";
import AdminCard from "@/components/admin/common/AdminCard";
import { AdminButton, AdminModuleEmptyState, AdminModuleHeader, AdminModulePage, AdminSectionTitle, AdminStatusChip } from "@/components/admin/design-system";
import { notificationPreferenceGroups } from "./notificationPreferencePolicy.mjs";
export default function NotificationPreferencesModule({ initialItems = [], setupRequired = false }) {
  const [items, setItems] = useState(initialItems), [message, setMessage] = useState(""); const [pending, startTransition] = useTransition();
  const run = (action, optimistic) => startTransition(async () => { const result = await action(); setMessage(result.message); if (result.ok && optimistic) setItems((current) => current.map(optimistic)); });
  if (setupRequired) return <AdminModulePage><AdminModuleHeader eyebrow="Persönlich" title="Benachrichtigungseinstellungen" description="Lege fest, welche optionalen In-App-Meldungen du zukünftig erhältst." actions={<AdminButton href="/admin/notifications">Zurück zu Benachrichtigungen</AdminButton>} /><AdminModuleEmptyState icon={Bell} title="Technische Vorbereitung erforderlich" description="Die Einstellungstabelle ist noch nicht eingerichtet. Bis dahin bleiben alle Benachrichtigungen wie bisher aktiviert." /></AdminModulePage>;
  return <AdminModulePage><AdminModuleHeader eyebrow="Persönlich" title="Benachrichtigungseinstellungen" description="Lege fest, welche optionalen In-App-Meldungen du zukünftig erhältst." actions={<AdminButton href="/admin/notifications">Zurück zu Benachrichtigungen</AdminButton>} /><AdminCard className="p-5 text-sm leading-6 text-white/60">Erforderliche Benachrichtigungen können nicht abgeschaltet werden. Änderungen betreffen nur zukünftige In-App-Meldungen; vorhandene Meldungen bleiben erhalten. Deine Einstellungen sind ausschließlich für dich sichtbar.</AdminCard><div className="flex flex-wrap gap-3"><AdminButton disabled={pending} onClick={() => run(enableAllOptionalNotificationsAction, (item) => item.configurable ? {...item,enabled:true}:item)}>Alle optionalen aktivieren</AdminButton><AdminButton disabled={pending} onClick={() => run(disableAllOptionalNotificationsAction, (item) => item.configurable ? {...item,enabled:false}:item)}>Alle optionalen deaktivieren</AdminButton><AdminButton disabled={pending} onClick={() => run(resetNotificationPreferencesAction, (item) => ({...item,enabled:true}))}>Standard wiederherstellen</AdminButton></div>{message ? <p role="status" className="text-sm text-white/65">{message}</p> : null}{notificationPreferenceGroups.map((group) => { const groupItems = items.filter((item) => item.group === group.key); return groupItems.length ? <section key={group.key} className="space-y-3"><AdminSectionTitle title={group.label} /><AdminCard className="divide-y divide-white/10 p-0">{groupItems.map((item) => <div key={item.type} className="flex min-h-20 items-center justify-between gap-4 px-5 py-4"><div><p className="font-bold text-white">{item.label}</p><p className="mt-1 text-sm text-white/50">{item.description}</p></div>{item.mandatory ? <AdminStatusChip variant="success"><CheckCircle2 size={14} /> Erforderlich</AdminStatusChip> : <button type="button" role="switch" aria-checked={item.enabled} aria-label={`${item.label} ${item.enabled ? "deaktivieren" : "aktivieren"}`} disabled={pending} onClick={() => run(() => updateNotificationPreferenceAction(item.type, !item.enabled), (entry) => entry.type === item.type ? {...entry,enabled:!item.enabled}:entry)} className={`relative h-11 w-16 shrink-0 rounded-full border transition focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-400 ${item.enabled ? "border-emerald-400/50 bg-emerald-500/35" : "border-white/15 bg-white/5"}`}><span className={`absolute top-1.5 h-7 w-7 rounded-full bg-white transition ${item.enabled ? "left-7" : "left-1.5"}`} /></button>}</div>)}</AdminCard></section> : null; })}</AdminModulePage>;
}
