import ArchiveButton from "@/components/admin/archiving/ArchiveButton";
import { removeTeamWithScopeAction } from "@/app/admin/teams/actions";
import { FormAlert } from "@/components/admin/forms";
import { formatContributionAmount } from "@/components/admin/contributions/helpers/contributionFormatters";
import ContributionStatusBadge from "@/components/admin/contributions/components/ContributionStatusBadge";
import { AdminActionBar, AdminButton, AdminDangerZone, AdminDetailHeader, AdminDetailLayout, AdminInformationRow, AdminInformationSection, AdminListChevron, AdminListHeader, AdminListMobileCard, AdminListRow, AdminMetric, AdminModuleCards, AdminModuleEmptyState, AdminModuleList, AdminModuleSummary, AdminStatusChip } from "@/components/admin/design-system";
import PlayerAvatar from "@/components/admin/players/components/PlayerAvatar";
import CoachAvatar from "@/components/admin/coaches/components/CoachAvatar";

const PLAYER_TEMPLATE = "3.5rem minmax(12rem,1.4fr) minmax(8rem,0.8fr) 7rem minmax(10rem,1fr) 7rem 3rem";
const COACH_TEMPLATE = "3.5rem minmax(12rem,1.4fr) minmax(9rem,1fr) minmax(8rem,0.8fr) 7rem 3rem";
const amount = (status) => status?.hasContribution ? formatContributionAmount(status.amountOutstanding || "0.00") : "–";

export default function TeamContributionDetailView({ team, canEdit = false, canArchive = false, activeCoachAssignments = 0, contributionVisibility = "none", contributionSeasonWarning = "", teamSummary = null, players = [], coaches = [] }) {
  const dangerZone = canArchive && team.is_active !== false ? <AdminDangerZone description="Die Mannschaft wird inaktiv. Aktive Spieler- und Trainerzuordnungen werden beendet; Personen, historische Zuordnungen, Beiträge und Zahlungen bleiben erhalten. Eine Reaktivierung ordnet niemanden automatisch wieder zu."><ArchiveButton entity="team" name={team.name_de} action={removeTeamWithScopeAction.bind(null, team.id)} playerAssignments={team.playerCount} coachAssignments={activeCoachAssignments} /></AdminDangerZone> : null;
  const headerActions = canEdit ? <AdminActionBar><AdminButton href={`/admin/teams/edit/${team.id}`} variant="primary">Bearbeiten</AdminButton></AdminActionBar> : null;
  const playerColumns = [{ key: "avatar", label: "Profil" }, { key: "name", label: "Spieler" }, { key: "position", label: "Position" }, { key: "status", label: "Status" }, { key: "contribution", label: "Beitrag" }, { key: "open", label: "Offen" }, { key: "details", label: "" }];
  const coachColumns = [{ key: "avatar", label: "Profil" }, { key: "name", label: "Name" }, { key: "role", label: "Funktion" }, { key: "license", label: "Lizenz" }, { key: "status", label: "Status" }, { key: "details", label: "Übersicht" }];

  return <AdminDetailLayout header={<AdminDetailHeader backHref="/admin/teams" backLabel="Zurück zu Mannschaften" backVariant="pill" title={team.name_de} status={<AdminStatusChip variant={team.is_active === false ? "warning" : "success"}>{team.is_active === false ? "Inaktiv" : "Aktiv"}</AdminStatusChip>} meta={`${team.age_group || "Mannschaft"} · ${team.seasonName || "Keine Saison"}`} actions={headerActions} backgroundImageUrl={team.team_image_url} backgroundPosition="center 38%" />} dangerZone={dangerZone}>
    {contributionVisibility === "none" ? <FormAlert className="border-white/10 bg-white/[0.04] text-white/75" tone="warning">Für deine Rolle werden keine Beitragsdaten angezeigt.</FormAlert> : null}
    {contributionSeasonWarning ? <FormAlert className="border-amber-400/30 bg-amber-500/10 text-amber-50" tone="warning">{contributionSeasonWarning}</FormAlert> : null}
    <AdminInformationSection title="Mannschaftsinformationen"><AdminInformationRow label="Bereich">{team.age_group || "–"}</AdminInformationRow><AdminInformationRow label="Saison">{team.seasonName || "–"}</AdminInformationRow><AdminInformationRow label="Spieler">{team.playerCount}</AdminInformationRow><AdminInformationRow label="Trainer">{activeCoachAssignments}</AdminInformationRow><AdminInformationRow label="Beschreibung">{team.description_de || "–"}</AdminInformationRow></AdminInformationSection>
    {teamSummary && !contributionSeasonWarning ? <AdminInformationSection title="Beitragsübersicht"><AdminInformationRow label="Aktuelle Saison"><AdminModuleSummary><AdminMetric label="Spieler" value={teamSummary.playerCount} /><AdminMetric label="Bezahlt" value={teamSummary.paidCount} /><AdminMetric label="Teilweise" value={teamSummary.partiallyPaidCount} /><AdminMetric label="Offen" value={teamSummary.openCount} /><AdminMetric label="Überfällig" value={teamSummary.overdueCount} /><AdminMetric label="Fehlt" value={teamSummary.missingContributionCount} /><AdminMetric label="Offen gesamt" value={formatContributionAmount(teamSummary.totalOutstanding)} /></AdminModuleSummary></AdminInformationRow></AdminInformationSection> : null}
    <section><h2 className="mb-4 text-xl font-black text-white">Trainer und Betreuer</h2>{!coaches.length ? <AdminModuleEmptyState title="Keine Trainer zugeordnet" description="Dieser Mannschaft sind aktuell keine Trainer oder Betreuer zugeordnet." /> : <AdminModuleList desktopClassName="hidden overflow-hidden xl:block" mobile={<AdminModuleCards className="xl:hidden">{coaches.map((coach) => <AdminListMobileCard key={`${coach.id}-mobile`} href={coach.detailHref} label={coach.detailHref ? `Details zu ${coach.displayName}` : undefined}><div className="flex min-h-11 gap-3"><CoachAvatar coach={coach} /><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><div><p className="font-black text-white">{coach.displayName}</p><p className="text-sm text-white/55">{coach.assignmentRoleLabel}</p></div>{coach.detailHref ? <AdminListChevron label={`Details zu ${coach.displayName}`} /> : null}</div><p className="mt-2 text-sm text-white/65">Lizenz: {coach.licenseLabel}</p><div className="mt-3"><AdminStatusChip variant={coach.isActive ? "success" : "warning"}>{coach.isActive ? "Aktiv" : "Inaktiv"}</AdminStatusChip></div></div></div></AdminListMobileCard>)}</AdminModuleCards>}><AdminListHeader columns={coachColumns} template={COACH_TEMPLATE} />{coaches.map((coach) => <AdminListRow key={coach.id} href={coach.detailHref} label={coach.detailHref ? `Details zu ${coach.displayName}` : undefined} template={COACH_TEMPLATE}><CoachAvatar coach={coach} sizeClassName="h-10 w-10" /><span className="truncate font-bold text-white">{coach.displayName}</span><span className="truncate text-white/65">{coach.assignmentRoleLabel}</span><span className="truncate text-white/65">{coach.licenseLabel}</span><AdminStatusChip variant={coach.isActive ? "success" : "warning"}>{coach.isActive ? "Aktiv" : "Inaktiv"}</AdminStatusChip>{coach.detailHref ? <AdminListChevron label={`Details zu ${coach.displayName}`} /> : <span className="text-xs text-white/40">Kein Zugriff</span>}</AdminListRow>)}</AdminModuleList>}</section>
    {contributionVisibility !== "none" && !contributionSeasonWarning ? <section><h2 className="mb-4 text-xl font-black text-white">Spieler und Vereinsbeiträge</h2>{!players.length ? <AdminModuleEmptyState title="Keine Spieler zugeordnet" description="Für diese Mannschaft liegen in der aktuellen Saison keine aktiven Spielerzuordnungen vor." /> : <AdminModuleList desktopClassName="hidden overflow-hidden xl:block" mobile={<AdminModuleCards className="xl:hidden">{players.map((player) => <AdminListMobileCard key={`${player.id}-mobile`} href={`/admin/players/${player.id}`} label={`Details zu ${player.displayName}`}><div className="flex gap-3"><PlayerAvatar player={player} /><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><div><p className="font-black text-white">{player.displayName}</p><p className="text-sm text-white/50">{player.assignmentLabel}</p></div><AdminListChevron label={`Details zu ${player.displayName}`} /></div><div className="mt-3 flex flex-wrap gap-2"><AdminStatusChip variant={player.isActive ? "success" : "warning"}>{player.isActive ? "Aktiv" : "Inaktiv"}</AdminStatusChip><ContributionStatusBadge status={player.contributionStatus?.status || "none"} isOverdue={player.contributionStatus?.isOverdue} compact /></div><p className="mt-3 text-sm text-white/65">Offen: {amount(player.contributionStatus)}</p></div></div></AdminListMobileCard>)}</AdminModuleCards>}><AdminListHeader columns={playerColumns} template={PLAYER_TEMPLATE} />{players.map((player) => <AdminListRow key={player.id} href={`/admin/players/${player.id}`} label={`Details zu ${player.displayName}`} template={PLAYER_TEMPLATE}><PlayerAvatar player={player} sizeClassName="h-10 w-10" /><span className="truncate font-bold text-white">{player.displayName}</span><span className="truncate text-white/65">{player.assignmentLabel}</span><AdminStatusChip variant={player.isActive ? "success" : "warning"}>{player.isActive ? "Aktiv" : "Inaktiv"}</AdminStatusChip><ContributionStatusBadge status={player.contributionStatus?.status || "none"} isOverdue={player.contributionStatus?.isOverdue} compact /><span className="font-bold text-white">{amount(player.contributionStatus)}</span><AdminListChevron label={`Details zu ${player.displayName}`} /></AdminListRow>)}</AdminModuleList>}</section> : null}
  </AdminDetailLayout>;
}
