"use client";

import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { mutateSupportTicketAdminAction, replySupportTicketAction } from "@/app/admin/support/actions";
import { AdminBackLink, AdminButton, AdminDetailHeader, AdminDetailLayout, AdminInformationRow, AdminInformationSection, AdminSectionTitle } from "@/components/admin/design-system";
import { SUPPORT_TICKET_LABELS, SUPPORT_TICKET_PRIORITIES, SUPPORT_TICKET_STATUSES, canReplyToTicketStatus } from "@/lib/support-tickets/supportTickets.core.mjs";
import { SupportTicketPriority, SupportTicketStatus } from "./SupportTicketStatus";

const DATE = new Intl.DateTimeFormat("de-DE", { dateStyle: "medium", timeStyle: "short" });
const FIELD = "min-h-11 w-full rounded-xl border border-white/10 bg-neutral-900 px-3 py-2.5 text-white outline-none focus:border-red-400";
const formatDate = (value) => value && !Number.isNaN(new Date(value).getTime()) ? DATE.format(new Date(value)) : "–";

function ReplyForm({ ticketId }) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [result, setResult] = useState(null); const [pending, startTransition] = useTransition();
  const submit = (event) => { event.preventDefault(); setResult(null); startTransition(async () => { const response = await replySupportTicketAction({ ticketId, message }); setResult(response); if (response.ok) { setMessage(""); router.refresh(); } }); };
  return <form onSubmit={submit} className="grid gap-3"><label className="grid gap-2 text-sm font-bold">Antwort<textarea required maxLength={10000} rows={5} value={message} onChange={(event) => setMessage(event.target.value)} className={`${FIELD} resize-y`} /></label>{result && !result.ok ? <p role="alert" className="text-sm text-red-300">{result.message}</p> : null}<div className="flex justify-end"><AdminButton type="submit" variant="primary" disabled={pending}>{pending ? "Antwort wird gespeichert …" : "Antwort senden"}</AdminButton></div></form>;
}

function Management({ ticket, assignees }) {
  const router = useRouter(); const [status, setStatus] = useState(ticket.status); const [priority, setPriority] = useState(ticket.priority); const [assignee, setAssignee] = useState(ticket.assignedToProfileId || ""); const [result, setResult] = useState(null); const [pending, startTransition] = useTransition();
  const save = (payload) => startTransition(async () => { setResult(null); const response = await mutateSupportTicketAdminAction({ ticketId: ticket.id, ...payload }); setResult(response); if (response.ok) router.refresh(); });
  return <section className="rounded-[1.5rem] border border-white/10 bg-white/[.04] p-5"><AdminSectionTitle eyebrow="Superadmin" title="Ticket verwalten" description="Status, Priorität und optionale Zuständigkeit kontrolliert ändern." /><div className="mt-5 grid gap-4 lg:grid-cols-3"><label className="grid gap-2 text-sm font-bold">Status<select value={status} onChange={(event) => setStatus(event.target.value)} className={FIELD}>{SUPPORT_TICKET_STATUSES.map((item) => <option key={item} value={item}>{SUPPORT_TICKET_LABELS.status[item]}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Priorität<select value={priority} onChange={(event) => setPriority(event.target.value)} className={FIELD}>{SUPPORT_TICKET_PRIORITIES.map((item) => <option key={item} value={item}>{SUPPORT_TICKET_LABELS.priority[item]}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Zuweisung<select value={assignee} onChange={(event) => setAssignee(event.target.value)} className={FIELD}><option value="">Nicht zugewiesen</option>{assignees.map((profile) => <option key={profile.id} value={profile.id}>{profile.full_name || "Aktiver Benutzer"}</option>)}</select></label></div>{result && !result.ok ? <p role="alert" className="mt-4 text-sm text-red-300">{result.message}</p> : null}<div className="mt-5 flex flex-wrap justify-end gap-3">{ticket.status === "completed" ? <AdminButton disabled={pending} onClick={() => save({ status: "open" })}>Ticket wieder öffnen</AdminButton> : null}<AdminButton variant="primary" disabled={pending} onClick={() => save({ status: status === ticket.status ? null : status, priority: priority === ticket.priority ? null : priority, assignedToProfileId: assignee || null, changeAssignment: assignee !== (ticket.assignedToProfileId || "") })}>{pending ? "Speichert …" : "Änderungen speichern"}</AdminButton></div></section>;
}

export default function SupportTicketDetail({ ticket, isSuperadmin = false, assignees = [], loadError = null }) {
  if (loadError || !ticket) return <div className="space-y-5"><AdminBackLink href="/admin/support">Zurück zu Support</AdminBackLink><p role="alert" className="rounded-2xl border border-red-500/20 bg-red-500/10 p-5 text-red-200">{loadError || "Ticket nicht gefunden oder kein Zugriff."}</p></div>;
  const replyAllowed = canReplyToTicketStatus(ticket.status);
  return <AdminDetailLayout header={<AdminDetailHeader backHref="/admin/support" backLabel="Zurück zu Support" eyebrow={ticket.ticketNumber} title={ticket.subject} status={<SupportTicketStatus status={ticket.status} />} meta={`${SUPPORT_TICKET_LABELS.category[ticket.category] || ticket.category} · ${ticket.areaLabel}`} />}>
    <AdminInformationSection title="Ticketinformationen"><AdminInformationRow label="Kategorie">{SUPPORT_TICKET_LABELS.category[ticket.category] || ticket.category}</AdminInformationRow><AdminInformationRow label="Bereich">{ticket.areaLabel}</AdminInformationRow><AdminInformationRow label="Status"><SupportTicketStatus status={ticket.status} /></AdminInformationRow>{isSuperadmin ? <AdminInformationRow label="Priorität"><SupportTicketPriority priority={ticket.priority} /></AdminInformationRow> : null}<AdminInformationRow label="Erstellt am">{formatDate(ticket.createdAt)}</AdminInformationRow><AdminInformationRow label="Letzte Aktivität">{formatDate(ticket.lastActivityAt)}</AdminInformationRow></AdminInformationSection>
    {isSuperadmin ? <Management ticket={ticket} assignees={assignees} /> : null}
    <section className="rounded-[1.5rem] border border-white/10 bg-white/[.04] p-5"><AdminSectionTitle eyebrow="Verlauf" title="Nachrichten" description="Alle Antworten werden chronologisch dargestellt." /><ol className="mt-5 space-y-4">{ticket.messages.map((message) => <li key={message.id} className={`max-w-3xl rounded-2xl border p-4 ${message.isOwnMessage ? "ml-auto border-red-500/25 bg-red-500/[.08]" : "mr-auto border-white/10 bg-black/20"}`}><p className="text-xs font-bold uppercase tracking-[.15em] text-white/45">{message.isOwnMessage ? "Du" : "Andere Person"} · {formatDate(message.createdAt)}</p><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-7 text-white/80">{message.body}</p></li>)}</ol></section>
    <section className="rounded-[1.5rem] border border-white/10 bg-white/[.04] p-5"><AdminSectionTitle title={replyAllowed ? "Antworten" : "Dieses Ticket ist abgeschlossen."} description={replyAllowed ? "Deine Antwort wird dem Ticketverlauf hinzugefügt." : isSuperadmin ? "Öffne das Ticket zuerst wieder, um eine weitere Antwort zu schreiben." : "Auf abgeschlossene Tickets kann nicht mehr geantwortet werden."} />{replyAllowed ? <div className="mt-5"><ReplyForm ticketId={ticket.id} /></div> : null}</section>
  </AdminDetailLayout>;
}
