"use client";

import { LifeBuoy } from "lucide-react";
import { AdminButton, AdminListChevron, AdminListHeader, AdminListMobileCard, AdminListRow, AdminMetric, AdminModuleCards, AdminModuleEmptyState, AdminModuleHeader, AdminModuleList, AdminModulePage, AdminModuleSummary } from "@/components/admin/design-system";
import { SUPPORT_TICKET_LABELS } from "@/lib/support-tickets/supportTickets.core.mjs";
import { SupportTicketPriority, SupportTicketStatus } from "./SupportTicketStatus";

const TEMPLATE = "8rem minmax(12rem,1.4fr) 8rem minmax(9rem,1fr) 11rem 10rem 2rem";
const DATE = new Intl.DateTimeFormat("de-DE", { dateStyle: "short", timeStyle: "short" });
const formatDate = (value) => value && !Number.isNaN(new Date(value).getTime()) ? DATE.format(new Date(value)) : "–";

export default function SupportTicketsModule({ tickets = [], isSuperadmin = false, canCreate = false, loadError = null }) {
  return <AdminModulePage>
    <AdminModuleHeader eyebrow="Hilfe & Rückfragen" title={isSuperadmin ? "Support-Tickets verwalten" : "Meine Support-Tickets"} description={isSuperadmin ? "Alle eingegangenen Support-Anfragen prüfen, beantworten und verwalten." : "Hier kannst du Anfragen stellen und den Bearbeitungsstand deiner eigenen Tickets verfolgen."} actions={canCreate && !isSuperadmin ? <AdminButton href="/admin/support/new" variant="primary">Neues Ticket</AdminButton> : null} />
    <AdminModuleSummary><AdminMetric label="Gesamt" value={tickets.length} /><AdminMetric label="Offen" value={tickets.filter((ticket) => ticket.status === "open").length} /><AdminMetric label="In Bearbeitung" value={tickets.filter((ticket) => ticket.status === "in_progress").length} /><AdminMetric label="Abgeschlossen" value={tickets.filter((ticket) => ticket.status === "completed").length} /></AdminModuleSummary>
    {loadError ? <p role="alert" className="rounded-2xl border border-red-500/20 bg-red-500/10 p-4 text-sm text-red-200">{loadError}</p> : null}
    {!loadError && !tickets.length ? <AdminModuleEmptyState icon={LifeBuoy} title={isSuperadmin ? "Noch keine Support-Tickets" : "Du hast noch keine Support-Tickets"} description={isSuperadmin ? "Sobald eine Anfrage eingeht, erscheint sie hier." : "Wenn du Unterstützung benötigst oder eine Verbesserung vorschlagen möchtest, kannst du ein Ticket erstellen."} actionHref={canCreate && !isSuperadmin ? "/admin/support/new" : null} actionLabel={canCreate && !isSuperadmin ? "Neues Ticket" : null} /> : null}
    {tickets.length ? <AdminModuleList desktopClassName="hidden overflow-hidden xl:block" mobile={<AdminModuleCards className="xl:hidden">{tickets.map((ticket) => <AdminListMobileCard key={ticket.id} href={`/admin/support/${ticket.id}`} label={`${ticket.ticketNumber}: ${ticket.subject}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-black uppercase tracking-[.16em] text-red-300">{ticket.ticketNumber}</p><h2 className="mt-1 break-words font-black text-white">{ticket.subject}</h2></div><AdminListChevron label="Ticket öffnen" /></div><div className="mt-3 flex flex-wrap gap-2"><SupportTicketStatus status={ticket.status} />{isSuperadmin ? <SupportTicketPriority priority={ticket.priority} /> : null}</div><dl className="mt-4 grid gap-2 text-sm text-white/60"><div className="flex justify-between gap-3"><dt>Kategorie</dt><dd className="text-right font-bold text-white/80">{SUPPORT_TICKET_LABELS.category[ticket.category] || ticket.category}</dd></div><div className="flex justify-between gap-3"><dt>Bereich</dt><dd className="text-right font-bold text-white/80">{ticket.areaLabel}</dd></div><div className="flex justify-between gap-3"><dt>Letzte Aktivität</dt><dd className="text-right font-bold text-white/80">{formatDate(ticket.lastActivityAt)}</dd></div></dl></AdminListMobileCard>)}</AdminModuleCards>}><AdminListHeader template={TEMPLATE} columns={[{ key: "number", label: "Ticket" }, { key: "subject", label: "Betreff" }, { key: "category", label: "Kategorie" }, { key: "area", label: "Bereich" }, { key: "status", label: "Status" }, { key: "activity", label: "Letzte Aktivität" }, { key: "open", label: "" }]} />{tickets.map((ticket) => <AdminListRow key={ticket.id} href={`/admin/support/${ticket.id}`} label={`${ticket.ticketNumber}: ${ticket.subject}`} template={TEMPLATE}><strong className="text-red-300">{ticket.ticketNumber}</strong><span className="truncate font-black">{ticket.subject}</span><span className="text-white/65">{SUPPORT_TICKET_LABELS.category[ticket.category] || ticket.category}</span><span className="truncate text-white/65">{ticket.areaLabel}</span><span className="flex flex-wrap gap-2"><SupportTicketStatus status={ticket.status} />{isSuperadmin ? <SupportTicketPriority priority={ticket.priority} /> : null}</span><span className="text-xs text-white/55">{formatDate(ticket.lastActivityAt)}</span><AdminListChevron label="Ticket öffnen" /></AdminListRow>)}</AdminModuleList> : null}
  </AdminModulePage>;
}
