"use client";

import { useMemo, useState } from "react";
import { AdminButton, AdminListChevron, AdminListHeader, AdminListMobileCard, AdminListRow, AdminMetric, AdminModuleCards, AdminModuleEmptyState, AdminModuleFilters, AdminModuleHeader, AdminModuleList, AdminModulePage, AdminModuleSummary, AdminStatusChip } from "@/components/admin/design-system";
import { filterTeamTypes, sortTeamTypes } from "./teamTypes.core";

const columns = ["", "Bezeichnung", "Anzeigename", "Altersklasse", "Status", "Sortierung", ""].map((label, index) => ({ key: `${index}-${label}`, label }));
const template = "3rem minmax(0,.7fr) minmax(0,1.2fr) minmax(0,1fr) minmax(0,.7fr) minmax(0,.55fr) 2rem";

export default function TeamTypesModule({ teamTypes = [] }) {
  const [status, setStatus] = useState("all");
  const sorted = useMemo(() => sortTeamTypes(teamTypes), [teamTypes]);
  const visible = useMemo(() => filterTeamTypes(sorted, status), [sorted, status]);
  const summary = { total: teamTypes.length, active: teamTypes.filter((item) => item.is_active !== false).length, inactive: teamTypes.filter((item) => item.is_active === false).length };
  const cards = <AdminModuleCards className="xl:hidden">{visible.map((item) => <AdminListMobileCard key={item.id} href={`/admin/settings/team-types/edit/${item.id}`} label={`${item.name_de} bearbeiten`}><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span aria-hidden="true" className="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-red-700 text-sm font-black text-white">{item.slug?.slice(0, 2).toUpperCase() || "TV"}</span><div className="min-w-0"><p className="font-black text-white">{item.slug?.toUpperCase()}</p><p className="mt-1 break-words text-sm text-white/60">{item.name_de}</p></div></div><AdminListChevron label="Vorlage öffnen" /></div><div className="mt-3 flex flex-wrap gap-2"><AdminStatusChip compact variant={item.is_active === false ? "warning" : "success"}>{item.is_active === false ? "Inaktiv" : "Aktiv"}</AdminStatusChip><span className="text-sm text-white/55">{item.age_group}</span></div></AdminListMobileCard>)}</AdminModuleCards>;
  return <AdminModulePage><AdminModuleHeader eyebrow="Einstellungen" title="Mannschaftsvorlagen" description="Verwalte die verfügbaren Mannschaftsbezeichnungen für den Verein." actions={<AdminButton href="/admin/settings/team-types/new" variant="primary">Neue Mannschaftsvorlage</AdminButton>} /><AdminModuleSummary><AdminMetric label="Gesamt" value={summary.total} /><AdminMetric label="Aktiv" value={summary.active} /><AdminMetric label="Inaktiv" value={summary.inactive} /></AdminModuleSummary><AdminModuleFilters title="Vorlagen filtern" panelId="team-type-filters"><label className="grid max-w-xs gap-2 text-sm font-bold text-white/65">Status<select value={status} onChange={(event) => setStatus(event.target.value)} className="h-11 rounded-xl border border-white/10 bg-[#17171d] px-3 text-white"><option value="all">Alle</option><option value="active">Aktiv</option><option value="inactive">Inaktiv</option></select></label></AdminModuleFilters>{visible.length ? <AdminModuleList mobile={cards} desktopClassName="hidden overflow-hidden xl:block"><AdminListHeader columns={columns} template={template} />{visible.map((item) => <AdminListRow key={item.id} href={`/admin/settings/team-types/edit/${item.id}`} label={`${item.name_de} bearbeiten`} template={template}><span aria-hidden="true" className="inline-flex h-9 w-9 items-center justify-center rounded-full bg-red-700 text-xs font-black">{item.slug?.slice(0, 2).toUpperCase() || "TV"}</span><span className="font-black text-white">{item.slug?.toUpperCase()}</span><span className="break-words text-white/70">{item.name_de}</span><span className="break-words text-white/60">{item.age_group}</span><AdminStatusChip compact variant={item.is_active === false ? "warning" : "success"}>{item.is_active === false ? "Inaktiv" : "Aktiv"}</AdminStatusChip><span className="text-white/60">{item.sort_order || 0}</span><AdminListChevron label="Vorlage öffnen" /></AdminListRow>)}</AdminModuleList> : <AdminModuleEmptyState title="Keine Mannschaftsvorlagen" description="Für den gewählten Filter sind keine Vorlagen vorhanden." />}</AdminModulePage>;
}
